### ISSUE TITLE
Slope vs Speed and Power suggestion

### ISSUE THREAD

**Issue by matthieudelcourt** [GoldenCheetah/GoldenCheetah#1088]
- In the case where the slope is absent in the bike computer data, I was wondering if it was possible to estimate the slope from the Distance and Altitude data.
- I think it would also be pretty cool to see in a long term trend chart how our speed and our power are changing over the year for slopes that are 5%, 10% 15%... I think they could be added to the metrics so we can call them in "Trends charts". For example: speed at 5%, speed at 10%, speed at 15%, power at 5%, power at 10%, power at 15%

**Comment by zisp** [comment]
This is exactly what I just attempted to plot on the scatter plot page (for running though, rather than cycling) and it doesn't seem like the slope calculation is working on anything except the ride page (where it colours the altitude plot by the slope).
Scatter plot with slope on x axis and power on y just shows a single point at 0,0 - it's not even showing the spread of power around a 0 slope (which seems odd, I thought it'd at least give a vertical line of dots.)

Attached a power vs altitude (which is working) and a power vs slope (which isn't) plot for reference.
![power vs slope](https://cloud.githubusercontent.com/assets/13761421/13893094/d73b6de6-edaf-11e5-8796-645c7d9d7d12.png)
![power vs altitude](https://cloud.githubusercontent.com/assets/13761421/13893095/d7889576-edaf-11e5-8d4e-d859e73537ee.png)

**Comment by jacoues** [comment]
+1 for this feature, the smoothed slope doesn't seem to work well in a scatter plot for activities. (GC 3.4). Is it possible to derive vertical speed as well? I would like to plot vertical speed vs altitude. I am curious to see how it varies on rides starting at ~1000m and ending at 2500-3000m.

**Comment by liversedge** [comment]
use r or python
