### ISSUE TITLE
Import TCX data from Polar Flow no register the power data

### ISSUE THREAD

**Issue by pakot8** [GoldenCheetah/GoldenCheetah#1212]
I try to import the data to GH and all is ok but the power sample don´t be register and don´t have samples of power to analize.
And the name of the dispositive is not polar keo power is Garmin.
I download the latest versión GH 3.1
Thanks

**Comment by Joern-R** [comment]
Just had a look at the file. Polar is using a different namespace reference for the schema (ns2) - where GC so far expected ns3 - or direct definition of the schemal. @Damien - if you haven't look at it yet - I can fix it tomorrow. Will also look for a generic approach on the namespaces in the XML extension.

**Comment by grauser** [comment]
Yes, Jörn I let you fix it, thank you.

**Comment by Joern-R** [comment]
Fixed with https://github.com/GoldenCheetah/GoldenCheetah/commit/5529bcff66c2b9b0a094f21a5c58e45d1fffcbf2

Until 3.11 is out you edit the file so that Watts are imported - You need to exchange "ns2" by "ns3" which is a prefix for Watts in the TCX schema extension supported in 3.1. Then Power is imported as well to GC.

I also found the project https://github.com/pcolby/bipolar which might be interesting for you.
