### ISSUE TITLE
Average TE wrongly calculated in GC 3.1 for OS X (Build ID 3100)

### ISSUE THREAD

**Issue by WillerZ** [GoldenCheetah/GoldenCheetah#1231]
I was surprised to see my average TE reported as 32.3% when looking at a turbo trainer FTP test ride. The normal range is 60-100%, and if my result of 32.3% were accurate it would mean I could double my FTP from a lowly 242W merely by improving to the *bottom* of the normal range, transforming me from Cat 4 into a world class athlete. The top of the normal range would make me a shoe-in for the hour record.

Sadly my dreams of signing for Team Sky later this year were dashed when I found that my actual average TE is 76%; so while I should get to 321W with perfect technique I will need to spend some time in the gym before the men in black come calling.

The bug appears to be that Golden Cheetah is including (as zero) data points for which there was no TE recorded when calculating the average TE.

There are of course two other possibilities: my O_Synce Navi2Coach head unit could be putting zero data points for TE into the .fit file when it shouldn't; or my Stages power meter is sending zero data points for TE when it shouldn't.

To try and eliminate these possibilities I uploaded the file to cyclinganalytics.com to see what they calculated as the average TE: they calculated 76%.

**Comment by WillerZ** [comment]
I had a cursory look through the code and it looks like the data model requires that all fields which exist at any time are populated at all times; if this impression is correct the fix is to copy the previous existing TE value forwards over the subsequent missing periods.

The same problem seems to exist for pedalling smoothness (PS) and the corresponding solution seems appropriate.

**Comment by liversedge** [comment]
Run Fix Gaps to correct the data which has missing samples.

**Comment by WillerZ** [comment]
@liversedge Tried Fix Gaps, it did nothing. I used Tolerance 1.0 and Stop 4.0.

**Comment by liversedge** [comment]
Oh, in that case I guess that in some cases the headunit actually 
records 0 -- I'll change the averaging to exclude zeroes.

**Comment by WillerZ** [comment]
@liversedge I can confirm the the head unit does not erroneously record zeroes: using the decode sample from gamin's FIT SDK I see a combination of records with 12 fields (no Left TE or Left PS entries) and records with 14 fields (the same 12 plus Left TE and Left PS). There are 1089 records including left TE and only one record with zero for Left TE.

**Comment by liversedge** [comment]
In your opinion post you talked about interpolation, now you are saying there are almost no zero values ?
Can you clarify ?

**Comment by WillerZ** [comment]
Example .fit file here: https://www.dropbox.com/s/5198dlh0m6ylhtl/20150110_102320.fit?dl=0

**Comment by WillerZ** [comment]
There are no zeroes in the .fit file, there are zeroes in the data in the edit screen after I import it to GC. The average from GC is the sum of all TE values divided by the count of all records including records which do not contain a TE value. It should be the sum of all TE values divided by the count of all records which contain a TE value.

**Comment by liversedge** [comment]
the values in the edit screen are absolutely from the fit file !

We do not interpolate data ever (other sites/sw might) .. I'm not sure this isn't a problem with the headunit or use of smart recording, but am happy to remove zero values from the TE average :)

**Comment by WillerZ** [comment]
@liversedge The values in the edit screen show the same number of fields from every time point in the FIT file. The fit file does not contain the same number of fields at every time point. Therefore it is obviously wrong to say that the edit screen only shows what is in the FIT file: if the given time point contains no datum for left TE the edit screen shows it as 0.

Please import the FIT file from the link I gave above and confirm this behaviour for yourself.

**Comment by liversedge** [comment]
http://en.wikipedia.org/wiki/If_a_tree_falls_in_a_forest

**Comment by WillerZ** [comment]
Its a basic feature of the FIT protocol that not every field has to exist at every time. Absence of data in the FIT protocol is distinctly different from the presence of a zero value.

Altering GC to ignore zeros will be nearly correct as almost all the zeroes it is working with were made up by the GC importer.

TE is only calculable once per pedal revolution and therefore *cannot* exist at every second if the cadence is under 60 rpm. It seems that the Stages PM calculates it as an average over 2-3 revolutions so it's not present every second even when cadence is >= 60rpm.

**Comment by liversedge** [comment]
If the data is not recorded (for whatever reason) then we won't invent it, much the same reason that Osynce don't.

But we can remove zero values from the average in this instance.

**Comment by liversedge** [comment]
Ah. It looks like the ANT protocol wants the data interleaved. My bad. Will interpolate.
![screenshot from 2015-01-11 12 38 47](https://cloud.githubusercontent.com/assets/142876/5695235/eea97714-998e-11e4-8baa-5b9f48375c50.png)

**Comment by liversedge** [comment]
Sorry !

**Comment by WillerZ** [comment]
Whether It depends what you mean by "interpolate": TE only exists when I am pedalling, so on a long descent if I don't pedal for 10 minutes it is nonsense for me to ask what the average TE for that period was.

I wonder if it is worthwhile to explore storing NaN instead of zero for missing values generally: that's a more natural value to represent "who knows" in some senses. It would mean a bunch of work to deal with it in the stats routines. If you don't have a philosophical objection to NaN values I will fork GC and have a look at what would be required.

**Comment by WillerZ** [comment]
I didn't like what using NaN would do to the rest of the code, so I have started an alternative approach inspired by the Option type from Scala et al.

In https://github.com/WillerZ/GoldenCheetah/tree/missing-datum-null I have defined a new datatype OptionDouble which is logically either a double with a valid value (what would be Some(x) in Scala) or an undefined value (what would be None in Scala). All of RideFilePoint's previously double fields now use OptionDouble and everything still builds.

Next I will change the importers use the `None` value of OptionDouble when a value is absent and then the stats routines to handle the change.

**Comment by liversedge** [comment]
What are you trying to achieve?
Sounds like a LOT of change / risk for little return?

**Comment by Joern-R** [comment]
I had a look at my TE/TS averages in Garmin Connect (as they invented this metrics) and searched if there is somewhere a description how to "average" (e.g. in the forums). Based on the definition (here in a very good explanation 
https://www.cyclinganalytics.com/blog/2014/04/torque-effectiveness-and-pedal-smoothness)
my suggestion would be to only consider the positive values in building the average.

When looking at how TE is calculated (P+ + P−) / P+ that means "Zero" will only occur if 
- no force is applied at all
- P+  == P- (not very likely in full revelation - or only if the rider is not really applying power - so useless data)

Pedal Smoothness similar - Pmax/Pavg - get zero if Pmax = Pavg = Zero.

So any Zero is either because the data was not sent/interleaved (since it probably was the same then the sample before) - or because the rider was not pedaling. Which I consider both as "not relevant" for build an average for this metrics.

I can give it a try and do a test to create the averages by using only the >0 data points and just divide through the number of > 0 samples. Then compare the results to what Garmin Connect shows to see if it fits.

When adding the metrics to Train (Real Time) I noticed always a little delay in sending / changing of data - compared to what I did on the trainer. And also my head-unit had this delay (showing the last reading - even if I already stopped pedaling / or showing Zero even if I was already pedaling a few seconds).

**Comment by Joern-R** [comment]
Just patched the Average Calculation for TE and PS as mentioned before. Result is exactly the same as shown on the Garmin Connect Website (with just one difference - GC has one decimal) and Garmin's rounding seems a bit different - it looks like they go fro 0.3 on to next upper and 0.2 and less to next lower full %.

Since I just an Edge tracking TE/PS this year - just 6 Rides - but they all fitted.

Shall I create a pull request?

**Comment by liversedge** [comment]
I am surprised it is the same, given each recorded value may represent a different number of seconds.. e.g LTE 50,0,0,0,60,0,65 non-zero average would be 175/3=58.3 using your approach, but if the values are interpolated you get: 50,52.5,55,57,60,62.5,65 which would be 402/7=57.4.

I don't think ignoring zeroes is enough, and also need to take into account when cadence/power is zero. But then, if thats how Garmin do it, then maybe we should defer to them ????

**Comment by WillerZ** [comment]
TE is not zero when cadence is zero. TE is undefined when cadence is zero. 

-----Original Message-----

**Comment by Joern-R** [comment]
You are right - when creating the average I have also "ignored" the rideTimeSecs - and take the number of samples available > 0. My understanding of the metrics is that it's data is per discrete "turn/revelation" - and does not consider how fast/slow you do that. So using time or cadence for interpolating or averaging seems not the right way.

**Comment by liversedge** [comment]
make sense. although the value is recorded every 3-5s which is typically more than enough time for 2 or more revolutions of the pedals. But since it is a higher order function then the non-zero averaging approach is the only one that makes sense, the ANT+ docs do mention the head unit averaging to account for interleaving but it is not clear what that would be.

TE when cadence is zero seems to make no sense, certainly its not effective, even if there is torque! 

I would say that conceptually TE is zero at zero cadence since there is no effective use of whatever forces are being applied :)

**Comment by Joern-R** [comment]
When I did the Real Time tracking and traced the message as they came in I noticed that even when the crank stood still - sometime/not always another TE/PS message was delivered. All the message had data - and the headunit showed the data for a few seconds, before either going to Zero - when no new message came and changed to the next delivered data.

I will push a proposal for averages - which for me creates the same Avg. as shown on Garmin Connect. Since my test account on Cyclinganalytics has ended - would be interesting to have someone validating this against their Averages as well.

**Comment by WillerZ** [comment]
Can I assume that you are not at all interested in altering the data model to distinguish values which are present from values which are not?

**Comment by liversedge** [comment]
It is something we have looked at before; you will see that for temperature for example we have a value NoTemp which is used to indicate temperature is not present. Its quite a thorny problem to resolve without massive changes — sensor data is used absolutely everywhere.

The bigger issue is regarding a more extensible approach to adding new series. As Garmin, Shimano, Moxy, BSX etc are introducing new series all the time we need a better way of adding new ones without lots and lots of cut and paste across the charts (e.g. allplot is a nightmare).

If there was a burning reason to do it then it would be a higher priority !

I get the impression you have capabilities that might be better applied to something of more value ?
Also, I will likely hold back from committing a massive change from a new contributor — just too risky.

Cheers

Mark

**Comment by WillerZ** [comment]
Fair enough.

I would address the there-are-always-more-data-series-being-added problem by defining that each data series is a singleton descended from a common `DataSeries` parent (this is better than an enum because they can know their own serialisation name, display name, units, valid range, etc). A factory class needs to have the mapping from serialisation names to class names to allow deserialisation.

`RideFilePoint` then uses a `Map<DataSeries,double>` to store its content at runtime and has a single accessor method `iteratorForDataSeries` that returns an `iterator<double>` with either one or zero elements to iterate over. A similar method `iteratorForDataSeries` on `RideFile` would get an `iterator<double>` over all the existent values of the given `DataSeries` which would allow all of the aggregate stats routines to be entirely generic.

I don't think actually think this would be very much work…mostly it's deleting lines of code.
