### ISSUE TITLE
linking can't find libqwt.a

### ISSUE THREAD

**Issue by ehrlinger** [GoldenCheetah/GoldenCheetah#1247]
On new git clone, GC compiles to linking. Linker is looking for ../qwt/lib/libqwt.a when the file is in ../qwt/src/libqwt.a

Related to #1180?

**Comment by liversedge** [comment]
Almost certainly .. I will take a peek.

**Comment by ehrlinger** [comment]
Still getting this...

at linking statement:
clang: error: no such file or directory: '../qwt/lib/libqwt.a'
make[1]: *** [GoldenCheetah.app/Contents/MacOS/GoldenCheetah] Error 1
make: *** [sub-src-make_default-ordered] Error 2

But:
> find . -name libqwt.a
./qwt/src/libqwt.a

Am I doing something else wrong in the setup?

**Comment by liversedge** [comment]
You need to rerun qmake and make in qwt/src for the changes to be applied.
The adjustment to the QWT src.pro moved where the lib was created from lib to src, I have moved it back.

**Comment by ehrlinger** [comment]
I did the 

make distclean; qmake build.pro; make 

and still get the error.

**Comment by liversedge** [comment]
You need to rerun qmake and make in *qwt/src for the changes to be applied*
The adjustment to src.pro was in the qwt/src directory.

**Comment by ehrlinger** [comment]
Actually... I don't think we're quite there.
In a new clone, from the developers manual

```
git clone git://github.com/GoldenCheetah/GoldenCheetah.git
cd GoldenCheetahj
cp src/gcconfig.pri.in src/gcconfig.pri
cp qwt/qwtconfig.pri.in qwt/qwtconfig.pri
qmake build.pro
make
```

Still give me:
```
clang: error: no such file or directory: '../qwt/lib/libqwt.a'
make[1]: *** [GoldenCheetah.app/Contents/MacOS/GoldenCheetah] Error 1
make: *** [sub-src-make_default-ordered] Error 2
```

And:
```
 find . -name libqwt.a
./qwt/src/libqwt.a
```

**Comment by ehrlinger** [comment]
I should add that manually copying the (long) link command, and changing `../qwt/lib/libqwt.a` to `../qwt/src/libqwt.a` works fantastically.

I have no confidence in my ability to patch this.

**Comment by liversedge** [comment]
Joern is looking into it ...

**Comment by Joern-R** [comment]
Hi John,

sorry - very nasty/un-expected side effect of a previous change. For me it's a bug in the QMake command $$replace for "spaces" - which just deletes the whole input text if it's mixed Upper and lower case - in the path name. Which is common and cause the problem for me as well.

I have pushed a patch (which still needs to be added to the master) - which is mainly the src.pro file taken from the latest version (6.12) of the QWT library - I have tested both in-source and out-of-source builds - both worked fine (on Windows) - and since this is similar to what we had before - I am quite confident this fixes the problem.

Again - due to the change - you need to go through

make distclean; qmake build.pro; make

to get the change in src.pro safely applied. If it's not working with this, please let us know. 
Thanks for your patience.
Joern

**Comment by ehrlinger** [comment]
Done. Fixed hurray!

**Comment by liversedge** [comment]
woot. If you want the job done right you need German engineering !
