### ISSUE TITLE
Synchronisation Tools for Athletes and Coaches

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1416]
The TrainingPeaks synch is kinda neat but for one athlete only, and it doesn't support syncing with other services or syncing config such as zones, CP etc.

We should extend the sync concept to be more feature complete:
* support dropbox + other services curently supported via 'share'
* add support for syncing more than just activities;configuration files like zones, preferences, seasons and segments
* add support for syncing multiple athletes

**Comment by liversedge** [comment]
As part of the prep for planning / coaching / self coaching this has been brought into v3.3 with a goal of unifying the whole upload/download/sync functionality across services.

**Comment by liversedge** [comment]
Need to distinguish between online services like TP that want activities with data stores -- e.g. we could share config and GC specific things via dropbox...

**Comment by Joern-R** [comment]
Did some searching if there is a common denominator on the different Cloud Services APIs. Looks like there is none. To a certain extent WebDAV is seen as common access approach. But popular services like DropBox do not offer this (there is a second commercial offering provided DropBox WebDAV access). So that means there is none.

Just had a first look at "taipirik.com" - it's an open source project & auto synchronization service. So it might be worth to investigate if GC can connect with "taipirik" - to be part of the synchronization chain. Even though taipirik is currently doing synchronization between Cloud based Trainingtools - that might be a way to have just one link from GC to most of the training Websites out there.

**Comment by liversedge** [comment]
I'm just going to stick to data storage solutions for now, data sync.
Initially just using dropbox, but can then extend to include google / apple / ms type solutions.

First step to authenticate with dropbox is done 15f470c3de9b201b56968eaf0d52a5f16656fcd1, will work on the gui/flow for syncing across PCs.

**Comment by liversedge** [comment]
Added FileStore base class and the beginnings of a Dropbox implementation in 3ab4d21a5e45d4c6d4cea2c8f6f0f080c7d71fe1

**Comment by liversedge** [comment]
Added file/directory chooser in 4e17a9970f34ca2a3cfb85f3facc301549e627ae. This will be reusable for dropbox/google/ms/icloud etc). You can now browse and select a folder on a cloud based file store in preferences.

![chooser](https://cloud.githubusercontent.com/assets/142876/10190925/ed41445e-6767-11e5-84a5-cab074502ebe.png)

**Comment by liversedge** [comment]
Upload to Dropbox added in 19203bba76da624577b070ebccb5cd6752163645 (with issues related to synchronous updates to be fixed).

**Comment by liversedge** [comment]
Sync dialog add in 17ed0815ec71f186de20120a49d268a0e884130a based upon TrainingPeaks dialog -- so could be unified in the future ....

**Comment by liversedge** [comment]
See #1580 for implementation of local store that can be used to map to google, ms, icloud folder.
