### ISSUE TITLE
Upload to Trainingstagebuch.org and Velo Hero does not work

### ISSUE THREAD

**Issue by Cyclenerd** [GoldenCheetah/GoldenCheetah#1472]
With GC RC 3 I get the following error if I want to share workouts at Trainingstagebuch.org or Velo Hero:

    request failed: Protocol "" is unknown

**Comment by liversedge** [comment]
Is this with our builds or your own?
Which OS are you on ?
Also, is this QT4 or 5 and 32 or 64 bit ?
Does it work with RC2 ?

Thanks
Mark

**Comment by Cyclenerd** [comment]
Hey Mark,

I have now tested a bit with RC4. I always use the version from the website.

My operating system is Mac OS X 10.10 64Bit.

The error seems to be related to the QT version:

* 64 Bit RC3 and RC4 with QT 5.4.2 = Upload not working
* 32 Bit RC4 with QT 4.8.7 = Upload works! (With RC3 untested)

Regards
Nils

**Comment by Joern-R** [comment]
Hi Nils,

Problem is not Mac specific - just tested with the Windows Build (64bit - QT 5.4.2) same error message.
The issue seems related to your use of QUrlQuery constructor. Documentation says, that it expects query parameter string to parse, you are providing the base URL of your service as query parameters.

I did a patch - which handles the QUrl separate from the Query and with this was able to upload. I suspect the same problem is on Trainingstagebuch - as the code follows the same logic.

Since Github does not let me add the patch here - and I want you to check/review first to then make the pull-request - I have sent the patch-file to "help at velohero.com".

Best regards.
Joern

**Comment by Joern-R** [comment]
Fix with 483e27090d49e1e0bff723ecd165c4a7e8aea8de
