### ISSUE TITLE
Adding sleep and resting HR

### ISSUE THREAD

**Issue by superdunn30** [GoldenCheetah/GoldenCheetah#1516]
Anyway we can add sleep hours and morning resting HR to the diary option? I have been searching for an easy track all your data site and this seems like an excellent place, but nowhere has the option for sleep and resting HR entry.

Thanks

**Comment by amtriathlon** [comment]
Probably https://groups.google.com/forum/#!forum/golden-cheetah-users is a better place for this questions, but anyway at the moment you can add any field you want as additional data for activities not for days, the way to do this is explained here: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Data%20Fields
OTOH numeric files are not supported for diary display but can be added as columns in the sidebar and the Navigator in Diary view as explained here: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Side%20Bar_Activities%20view#activities---column-header

**Comment by amtriathlon** [comment]
I've changed calendar text so that en future versions if you add Sleep Hrs and Resting HR as numeric metadata fields and check the diary checkbox they will be shown with field name as labels: https://github.com/GoldenCheetah/GoldenCheetah/issues/1524.
Anyway they will be attached to activities, so you still need at least one activity per day to input this values.
