### ISSUE TITLE
Threshold HR settings page is a time machine

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1634]
If I set my threshold HR test date as 01.07.15 which is supposed to be July 1, 2015, the actually added year is 1915.

**Comment by liversedge** [comment]
Don't use a 2 digit year.

**Comment by prokoudine** [comment]
What do you mea, don't use a 2 digit year? I have no choice.

**Comment by amtriathlon** [comment]
What locale you are using? I happens if you change your locale to English (UK or US)?
I think this is the same problem Joern fixed recently for file import dates: https://github.com/GoldenCheetah/GoldenCheetah/issues/1592

**Comment by prokoudine** [comment]
It's reproducible in Russian locale. It isn't in the English one.

**Comment by Joern-R** [comment]
If it's windows please check in "Region and Language" (hope translation
fits) the defined date format and make sure it's TT.MM.JJJJ.
That should fix it (had that in the past) - the fix is associated to
"fromString" in Import - which may also be a problem in other locales
that why we changed it to be locale independent.

2015-11-07 14:07 GMT+01:00 Alexandre Prokoudine <notifications@github.com>:

**Comment by prokoudine** [comment]
I'm on Linux on this computer.

**Comment by Joern-R** [comment]
Same thing - I just do not have a clue where to adjust this under Linux.

I tested it by changiing the Settings under windows to DD,MM.JJ and the
QDateEdit follows
that format. And in case of 2 digits initializes year to 2000.

From the QT documentation - "Note that if you specify a two digit year, it
will be interpreted to be in the century in which the date time edit was
initialized. The default century is the 21 (2000-2099)."





2015-11-07 14:52 GMT+01:00 Alexandre Prokoudine <notifications@github.com>:
