### ISSUE TITLE
Swim pace calculation error

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#1645]
Hi,

I'm manually entering my swim data, so just distance and time for the whole swim. The last few months, after 15 August, something seems wrong with the calculation of the average swim pace (min/100m). I believe this is around the date where I started using GC 3.2 on Ubuntu.  

These are some data before 15 August:
![image](https://cloud.githubusercontent.com/assets/14836910/11034119/4257fab4-86e9-11e5-9c26-25db074638c4.png)

GC seems to calculate pace correctly

And here are some data after 15 August:
![image](https://cloud.githubusercontent.com/assets/14836910/11034146/8b1d4b3c-86e9-11e5-92e0-a5adf8772224.png)

GC pace is off by 1-3 s/100m

Could this be a bug in GC 3.2?

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
The problem happens because Swim Pace es computed from Average Speed and, in Manual Workouts, Average Speed is truncated to 1 decimal place in km/h.
For example 3500m in 1h26min gives 2.44186km/h which corresponds to 2:27min/100m, but in the Manual Workout dialog it is truncated to 2.4km/h which corresponds to 2:30min/100m

**Comment by liversedge** [comment]
Should we increase the precision ?

**Comment by amtriathlon** [comment]
I think the precision of the Average Speed metric is not a problem in general since it affects only how the metric is displayed but the internal value is not truncated.
We could change avgKPH->setDecimals(1) in line 218 of ManualRideDialog to a higher value or avoid using it when the user don't override Average Speed and just use distance/duration, the first is simpler.

**Comment by amtriathlon** [comment]
Nigel: if you disable the Average Speed metric override for this workouts the problem is solved, just go to Details>Metric tab and uncheck the Average Speed checkbox.

Mark: I think the ability to override Average Speed in ManualRideDialog is overkill since it depends on Distance and Duration and is better changed from them, my proposal is to make avgKPH read-only and don't override Average Speed, we could show pace in proper units also.

**Comment by liversedge** [comment]
Yes, it is a bit weird to off that !

**Comment by nigelvdv** [comment]
Great, problem solved. The correct ones all had the average speed metric unmarked already. Finally seeing some progress in swim pace!

**Comment by amtriathlon** [comment]
I will change this so in v3.3 average speed is not overridden for manual workouts.

BTW, if you do intervals in your swimming workouts (highly recommended), you can have much finer control of your swim progress using the Lap Editor to enter them,

**Comment by amtriathlon** [comment]
The problem was introduced in v3.2 because of this commit: https://github.com/GoldenCheetah/GoldenCheetah/commit/efd3859d2e876af97be6e848435bda32a5be3dc3, before that Average Speed was initialized to zero and not overridden unless the user provided a value different from zero, I think we should revert to that behavior.
