### ISSUE TITLE
Add video synchronisation on OSX

### ISSUE THREAD

**Issue by vlcvboyer** [GoldenCheetah/GoldenCheetah#1675]
Seems easy by using mp->setPlaybackRate(qreal rate)
in VideoWindow.cpp:374 by adding, "GC_VIDEO_QT5" to "#ifdef GC_VIDEO_VLC"
and then separate libvlc and QT with #ifdef at the few locations where it is used:

436:libvlc_media_player_set_time(mp, (libvlc_time_t) (rfp.secs_1000.0));
by adding for QT5 something like:
       mp->setPosition(rfp.secs_1000);

442:libvlc_media_player_set_pause(mp, (rate < 0.01));
by adding for QT5 something like:
       if (rate < 0.01)
           // maybe use mp->pause()
           // but preferably:
           mp->setPlaybackRate(0.0)

447:libvlc_media_player_set_rate(mp, rate );
by adding for QT5 something like:
       mp->setPlaybackRate(rate)
...

I'll not do the modifications as I cannot test on OSX on my side...

**Comment by amtriathlon** [comment]
I am closing this since VLC support for macOS, including video sync support, was added in https://github.com/GoldenCheetah/GoldenCheetah/commit/1cb1beb09c435ce27e5f6c94a20351942925ef8d and VLC 3 was added to Travis-ci builds in https://github.com/GoldenCheetah/GoldenCheetah/commit/c10b666b5519f9cfae7e46759a83495515b5cde9
The guidelines to implement video sync with QT5 video will be added to https://github.com/GoldenCheetah/GoldenCheetah/issues/2242
