### ISSUE TITLE
GC 3.3 Problem

### ISSUE THREAD

**Issue by Peter2m** [GoldenCheetah/GoldenCheetah#1708]
When loading 3.3 the attached window appears.......in the RC3.3 editions the trend view charts have disappeared.....3.2 was working without problems.
![gc 3 3](https://cloud.githubusercontent.com/assets/11757365/11494993/ca85d1a2-9807-11e5-99de-3852291c6c47.PNG)

**Comment by liversedge** [comment]
Are you using the 3.3 release binary ?
This was a bug in RC2 that we fixed.

The charts have gone because you probably used 3.2 /after/ running 3.3 (which upgrades the chart config but then cannot be read by an earlier release). To fix it use View->Reset Layout and Chart Sidevar->Reset to Default in trend view.

**Comment by Joern-R** [comment]
You need to use the "trainDB' file from your Backup - the problem was cause by a "bad" fix in 3.3 RC0, RC1, which was fixed in RC2 - but "trainDB" is affected if you have used a RC before RC2 and needs to be reverted to the 3.2. backup.

**Comment by liversedge** [comment]
Joern ... If no backup is available can it just be deleted and recreated with a search from the train view sidebar?

**Comment by Peter2m** [comment]
I have in the meantime created the side bar new with only 1 column (date).....everything seems to be stable now......thanks for yr comments.

**Comment by Joern-R** [comment]
Yes - deleting TrainDB and recreating by using the search also fixes the
problem - sorry - forgot to mention before.

Joern

2015-12-01 12:21 GMT+01:00 Peter2m <notifications@github.com>:
