### ISSUE TITLE
MSVC build mem leak

### ISSUE THREAD

**Issue by bdb** [GoldenCheetah/GoldenCheetah#1775]
I was reviewing the FitRideFile (for a non-related purpose) and noticed that the MSVC support leaks mem in read_unknown() when allocating the temp buffer. I assume there's a reason to not allocate the buffer on the stack (small Windows thread stack size?).

A related aside, the naked new's all over the place in GC would be much better as std::unique_ptr or if C++11 can't be used a custom RAII class that serves the same purpose. A lot of the manual mem management code could be removed and the chance of these types of leaks creeping in would be reduced considerably.

**Comment by liversedge** [comment]
I don't think the read is even neccessary since the data is discarded, seek would be better.
TBF to Joern, the update for MSVC arrays was done to get the build working, I can imagine there are a few snafus along the way.

Thanks for pointing this one out.

Re: use of naked new, we have to take care with QT since, in general, widget ownership is passed to parent widgets and they are also deleted by them. Which is why you rarely see a delete statement for a QT widget.

**Comment by bdb** [comment]
Good info on Qt, but couldn't unique_ptr be used for all non-QT allocations? And do you still require pre-C++11 compatibility? I know this is off topic, but I'm interested. ;)

**Comment by liversedge** [comment]
I don't know of any reason we would mandate pre-C++11, OTOH its not a biggie for us. I wanted to use lamdas the other day (can't remember why, was around threading issues) but got by without them to avoid introducing a dependency without knowing its impact.

There are a couple of bodies buried regarding memory management in GC .. just grep XXX and you'll probably find them .. unique_ptr might also have consequences too.. sometimes we have interaction issues that mean deleting things can have catastrophic effects.. but thats also a code quality issue. just hard to fix!
