### ISSUE TITLE
New activities uploading, but not updating PMC trend curves 

### ISSUE THREAD

**Issue by isotonicake** [GoldenCheetah/GoldenCheetah#1805]
Over the last few days, my training sessions are uploading ok from a number of devices (garmin swim, 810 & 310xt) and are showing in my activity diary. 

However my PMC stress curve is not reflecting the training completed. 

Is there a way to resolve this issue? Thanks

**Comment by liversedge** [comment]
can you post a picture of the pmc chart date settings.

**Comment by jgonzi** [comment]
I have the same problem. I try to explain better:
- When I upload the activity of the Garmin that have Powermeter the PMC update automaticly. (Perfect)
- When I upload an activity that hasn't got a TSS, it didn't update the PMC, to this point ok, because it needs this value, but if I go to the activy and I put Details the TSS value calculate with an estimation it doesn't update the PMC graphic. The only solution I found is create a manual activity and there put the TSS and whit the manual activity it goes, but I don't have with this way all the information of the activity.

I hope that helps.

**Comment by liversedge** [comment]
Did you save the activity after updating TSS?

**Comment by jgonzi** [comment]
I did it. I also close the program and reopen it.

 The only way I found to go well is as I comment create a new manual activity, put the TSS, and after that see the PMC has changed and delete the manual activity and it reads the correct value from the TSS of the imported activity.

It seems has you said that could be something that doesn't update.

I suppose I will make more of this activity I will try to make a film. 

Date: Thu, 28 Jan 2016 13:45:22 -0800

**Comment by jgonzi** [comment]
I have do it today another time... 

When I put the TSS and save it it appears BIKE TSS activity but until I put the manual activity that later I delete it it doesn't update the PMC. 

So the problem I supose it could be that when you save the activity the PMC it is not recalculated with the new TSS and when I put the manual activity includes both TSS.

**Comment by amtriathlon** [comment]
I can not recreate this issue in current master: when the metric override is activated/changed in details the new value for the base metric and derived stress are automatically reflected in PMC charts, even without saving. Please test using the last development build and reopen with details if you can recreate.
