### ISSUE TITLE
crash using windows 7

### ISSUE THREAD

**Issue by lucas-garoto** [GoldenCheetah/GoldenCheetah#1825]
[crash report GC.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/112447/crash.report.GC.txt)

it happens occasionally  when i open GC. it asks me to select the "athlete profile" and then crashes.

i hope this is useful. 
if I have to provide any more info, just let me know

**Comment by Joern-R** [comment]
The crash report seen here mean that GC crashed the last time you have used it. Not when starting up. Since Windows does not have a technical crash log in place the only way to figure out the originating problem is if you find out under which circumstances you have closed GoldenCheetah so that on next start the crash report window appears.

Thanks.
