### ISSUE TITLE
Functional change request: Ignore existing files earlier during auto-import

### ISSUE THREAD

**Issue by batsonjay** [GoldenCheetah/GoldenCheetah#1892]
The current workflow (v3.3) when Auto-Import from a directory is enabled is:
1) GC is launched
2) GC obtains list of all files in target directory
3) GC validates the contents of all files in the folder
4) User selects Import; valid files are imported
5) IF a file has already been imported, the Import Status is set to "Error - Activity file exists"

I propose this is better:
1) GC is launched
2) GC obtains list of all files in target directory
3) If a file has already been imported, the Import Status is set to "Already imported"
4) GC validates any files that have not been imported
5) User selects Import; valid files are imported

The reason: Validation takes time, and should be skipped if the file exists.

Background: I have GC set to auto-import any files placed into a Dropbox folder by TrainerRoad. I like this.

However, with this setup, every time I open GC, I must wait for dozens of files to be validated. This would be solved if GC quickly detects (& skips) already-imported files.

**Comment by paulj49457** [comment]
Can you please take a look at pull request #3770 Auto import filtering and file import exclusion, as this provides a shorter importation duration of 30 days, and also allows files to be excluded, although having to mark each file for exclusion sounds like a lot of work, the exclusion is for specific duplicates you want to avoid. I think a shorter 30 days importation window will probably fix this issue, as the validated files are checked against the existing activities and if already present are ignored. I added the 30 days option because I have auto importation set to run at start-up and it was taking too long, 30 days has solved it for me.

**Comment by liversedge** [comment]
I think @paulj49457 fixes are ok, also Jay hasn't responded for a while so closing this.
