### ISSUE TITLE
Support for Kettler devices via bluetooth 

### ISSUE THREAD

**Issue by kaegi** [GoldenCheetah/GoldenCheetah#1999]
My `RUN 7` doesn't seem to be supported by Golden Cheetah, so I wrote a library that should make it very easy:

https://github.com/ChangSpivey/kdri

It should also provide support for other models, though they aren't tested. Since GC is the main purpose of `kdri`, I'm still open to breaking API changes (in case this is needed).

**Comment by liversedge** [comment]
Cool stuff !

Was there a reason you chose to use rust ?
How have you integrated this lib with GC, do you have a patch for that ?

Not sure how we could make this work as it stands in a cross platform way. 

Since there is already support for Bluetooth devices in the GC codebase using QT's BT support I think it would be better to support it natively ...

**Comment by ChangSpivey** [comment]
My choice for Rust: This is supposed to be a low-level library, so I limited myself to C, C++, Rust (or D). Since Rust makes memory management (among other things) so much easier I chose this language.

The library uses the `SDP` and `RFCOMM` interface of BlueZ. As far I as I know (https://stackoverflow.com/questions/6992333/does-qt-support-the-windows-bluetooth-api), QT does not support `RFCOMM` on windows. Is there any benefit of QT's BT?

**Comment by liversedge** [comment]
Yes Windows BT support is missing, which is a shame. We chose it since we're a QT app and (hopefully) they will support Windows in later releases.

Am I right in thinking you have not integrated this with GC?

Thanks

Mark

**Comment by ChangSpivey** [comment]
I'm currently restructuring `bluetooth-rs`, and because the bluetooth API on Windows is similar to BlueZ, I might implement support for it. macOS is more difficult, because it does not seem to use the POSIX socket API, but something more higher level.

The only cross platform BT libraries I found are written in Python (LightBlue) and Node.js (bluetooth-serial-port), which I don't like for `kdri`.

I don't have a patch right now but implementing a `KettlerBluetoothController.cpp` seems to be easy enough. Will the patch be accepted even if there is currently only Linux support?

**Comment by liversedge** [comment]
Sure we can accept the patch as an optional dependency, it may not be put into official builds.
But if you have a controller we might look to adapt it to the QT BT API, so it would be gratefully received.

**Comment by ChangSpivey** [comment]
The pull request implements the most important bits of the code, but it still has many rough edges. I faced some challenges, which I want to discuss here. I invested some time in this project, but the GC code base is large, so I don't know much apart from the section I worked in (there might be mistakes in my observations).

- first of all: the `RUN 7` is a treadmill, and though the library works for different kinds of devices (bikes should now work), I can only test on devices I have access to.
 - `setIncline()` and `setSpeed()` are needed in `RealtimeController`
 - there is no easy 1:1 relationship between the UI and the `RealtimeController` functions: `pause` and `restart` exist, but aren't called when the user presses the pause button in `TrainSidebar` (am I missing something?). The treadmill is supposed to stop and start its movements with these buttons.
 - you can start/stop the treadmill by pressing buttons on the device. There seems to be no function to receive these changes. 
- the whole program seems to be constructed for serial interfaces with fast access (not a big surprise)
 - the `AddSearch` was only designed for COM/USB ports - Bluetooth works different: it has one adapter/port (technically one could have multiple local Bluetooth adapters, however one is choosen by the Bluetooth library), but multiple devices that can be found with it. It might be a good idea for reusability to move all "port/devices"-logic into `*Controllers`, which then say whether they are a "one-port/one-device" "one-port/multiple-devices", "multiple-ports/one-device" or even "multiple-ports with multiple-devices" and then return lists of ports and for each port a list of devices. This way, the `AddDeviceWizard` doesn't need to know the underlying protocol for its UI. [I didn't want to create a new widget for only a slightly different behavior]
 - handling of connection errors is difficult: the program ignores the result of `RealtimeController::start()`. There is no way (?) to contact the program the connection was interrupted during `getReatimeData()`. I "solved" it by letting `KettlerBluetoothController` create error dialogs, which is bad from a design viewpoint (no separation between UI and backend) as well from a usability viewpoint (error dialogs keep popping up - the user can't even close the program).
 - reconnecting blocks for some seconds -> we can't just trying to do that again and again

I hope this clarifies what this code can do and what not.
Some remarks at the end: I will focus on other projects from now on, so I'll probably only be able to make small changes. Additionally I won't have access to a `RUN 7` in 2 months, which complicates development somewhat.

**Comment by ChangSpivey** [comment]
If you want to (re-)implement the `kdri_*` functions, I will write a protocol description. Just ask anytime.

**Comment by liversedge** [comment]
Thanks !

Will look through it, but see below to some of your points.

It's not written solely for serial devices. the port spec can be anything, the configuration dialog screen flows have multiple paths -- a new one may be needed for treadmills.

setGradient() sets the incline and setLoad() should be used for speed for treadmill devices -- the gui needs to take this into account. Not sure how pre-programmed "erg" files would work in "speed" mode for instance.

status is managed separately across threads, the ANT or Computrainer devices show how this works (threads terminate on error, start return code is not meaningful).

**Comment by ChangSpivey** [comment]
What is the current state of this patch and treadmills in general?

**Comment by liversedge** [comment]
I'm still struggling with this patch, mostly because
a) it uses rust
b) I can't test it.

I think I'm going to have to close it, I'm really sorry, but there isn't much demand for this support and it looks like creating a maintenance nightmare.

Apologies

Mark

**Comment by kaegi** [comment]
No problem :)
As a maintainer of several (smaller) open-source projects I understand your reasons very well. Besides: the code is now available for anyone who wants Kettler support - which is much better than having to reverse-engineer the protocol again.

**Comment by liversedge** [comment]
THANK YOU -- Much appreciated.
