### ISSUE TITLE
Tacx Flow Multiplayer - Can't find trainer

### ISSUE THREAD

**Issue by udjamaflip** [GoldenCheetah/GoldenCheetah#2028]
Hey,

The app doesn't seem to recognise the trainer while it's connected through USB port.
I tried the Tacx trainer software to make sure there's no connectivity issues and it sees the trainer perfectly.

Running on OS Windows 10
Tried with GC 3 & 4-dev

Cheers

**Comment by liversedge** [comment]
Its not supported, and unlikely to be supported as the protocol is secret.

**Comment by udjamaflip** [comment]
Sorry - I should've been prescriptive. I'm not referring to the multiplayer aspect - I'm referring to just the trainer.

This trainer works with GoldenCheetah on OSX.

**Comment by liversedge** [comment]
Really?

Blimey.

**Comment by udjamaflip** [comment]
It's the same driver as the Fortius so it can be connected through that same way.

**Comment by liversedge** [comment]
Here is an explanation from Dave W, the Fortius support author:

"The problem is driver signing on Windows 10 (something seems to have changed from Windows 7 or 8) Because the GC tacx driver is self signed it only seems to be trusted on the machine which created the installer. I've tried all sorts of options but the only thing which seems to work is for the user to create their own driver or to disable driver signing on Windows (or get a digital certificate for GC which is trusted by Windows)"

We're not going to get signed drivers anytime soon I'm afraid.
