### ISSUE TITLE
Bontrager Duotrap dropouts for speed/cadence

### ISSUE THREAD

**Issue by randar68** [GoldenCheetah/GoldenCheetah#2032]
Bontrager Duotrap speed/cadence sensors consistently drop speed and cadence data.  I have observed this on GC3.3 as well on all recent 4.0 Beta releases.  I generally run with a Powertap G3 as well, but I verified this issue persists even if I do not pair with the Powertap.  I also verified that it is not my PC/software competing for the ANT+/USB as I have been able to verify the consistent operation of the Duotrap sensor, Suunto ANT+ stick, and laptop I run on with other cycling/sensor software that does not exhibit this issue.

I'd be happy to supply logs, please advise what logs would be needed or how to generate appropriate data needed to debug.

**Comment by wizardofaz** [comment]
Have you resolved this issue? I'm wondering if my issue is the same. I'm using a Bontrager "Interchange Combo Sensor", Ant+/BT, Speed & Cadence. It provides speed and cadence data perfectly to my Garmin 910XT, but with GC I get near perfect cadence data, but pretty much unusable speed data, and therefore also unusable vpower data. The displayed number jumps around between what looks like the actual number, and various other values much less. Like half, or a quarter, or two thirds of the real number. The distance after the ride seems to reflect an average speed that matches the indicated speed, which is to say much less than the actual speed. 

Since my main objective was to have a way to do power based workouts, this problem has made GC pretty much useless with this sensor. Right now I don't have another sensor to see if it's really a sensor issue or something else.

**Comment by jacobrosenthal** [comment]
Open source analytics and presentation mostly for runners, but man, its a
start
https://github.com/GoldenCheetah/GoldenCheetah

**Comment by randar68** [comment]
@wizardofaz, I have not resolved.  I was with you, with this making power training useless with GC using the Trek/Bontrager duotrap but threw my powertap wheel on and bypassed the issue.  With my setup, I was confirm the Duotrap paired with and provided reliable data against my Samsung GS5 and 910xt as well as verifying the Garmin Speed/Cadence sensor on y road bike paired reliably with the same laptop/software.  

Don't know what to tell you aside from not being convinced this sensor is supported by GC unless presented with other evidence.  I've offered logs and debugging, but gotten no guidance or confirmation of issue being known.

**Comment by wizardofaz** [comment]
Thanks for the confirmation. I tried a different bike that has a Wahoo s/c sensor, it works fine with that. At least the speed and cadence data is steady and matches pretty closely what I see on the garmin. However, with that setup I get to the next issue: that bike has a powertap and the power numbers of the powertap and the vpower on GC are quite different, GC being about 15% higher. Moreover, the GC number at any given speed does not match the number expected from the speed/power mapping equation published by Kurt Kinetic. 

Many puzzles to figure out. Luckily, I have the garmin, so the rides all get measured and logged the way I want them. Would be nice to get GC working right though. I'd like to help a buddy get set up with it, and he has no powertap as a second source. 

Thanks.
