### ISSUE TITLE
.FIT Data file from Stryd - data interpretation new file format

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#2083]
The Stryd running powermeter collects a lot of data (HR, power, but also ground contact time, vertical oscillation) which is all saved to the .FIT file. However, due to a new file format, this data is interpreted wrongly by GC. Power, cadence, pace and HR are interpreted correctly, but other data is missing.

The team of Stryd is willing to provide support to help with the issues (please see http://club.stryd.com/t/iq-app-data-in-fit-data-file/2660/3). Thanks for all the effort!

**Comment by liversedge** [comment]
Do you have an example, there were a number of updates last week to fix this, but are not in the development builds yet.

If the gct et al are recorded as developer fields instead of just using native types then they will end up either in XDATA or in the proper series if they set native_field_num correctly.

Either way .. if you have a URL to a file we can try that would be great (or email me liversedge@gmail.com)

**Comment by grauser** [comment]
The last deve build (3.4) imports ground contact time, vertical oscillation
from Stryd.

What is your GoldenCheetah version ?

Le mer. 14 sept. 2016 à 14:55, Mark Liversedge <notifications@github.com> a
écrit :

**Comment by grauser** [comment]
Last update of Stryd IQ App corrected this issue.
Fit files from the Stry IQ app (FIT 2.0) are correctly imported with all data with the current code.

**Comment by Hezelnutt** [comment]
Thanks for the quick update!

**Comment by grauser** [comment]
If you use the phone app the issue corrected in the last Stryd IQ version was not a problem for you.
Could you send me (or attach here) a file to verify ?
Thank you.

**Comment by Hezelnutt** [comment]
I was using the Stryd IQ app. I own a 910 but have been testing a newer Garmin with the IQ apps. Sorry for the confusion, but my problem is solved correctly ;)
