### ISSUE TITLE
Add cursor vertical bar for charts in stacked view

### ISSUE THREAD

**Issue by morejiik** [GoldenCheetah/GoldenCheetah#2134]
Sometimes it will be very useful to have a vertical bar going across all the charts in **stacked view**. The current cursor is represented by a little cross. 
In this way it will be possible to identify the correlation between different measurements (like HR and Power or Power and L/R balance, etc). 

Thank you!
![vertical bar example](https://cloud.githubusercontent.com/assets/16487758/19245637/7679c902-8f22-11e6-917c-8d60a940c149.png)

**Comment by amtriathlon** [comment]
This facility is already available: left button click&drag over the x-axis shows a vertical reference line, if the button release happens over the axis the line is automatically deleted, otherwise you are presented a dialog offering to mark an exhaustion point. We should document this on the wiki https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_ChartTypes_Activities#performance
