### ISSUE TITLE
More for REST API

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2226]
Right know there are only reading features.

I think these features could be interesting:
* Upload activity through rest api
* Call processing functions

Example. Take activity (from garmin\strava\etc), upload it to the application, get start time of activity, check direction and wind speed in that time through weather web-site. Call estimate power value function with calculated parameters through rest api.
Of course, all these things do some script

**Comment by amtriathlon** [comment]
I am closing this since, from v3.6, these functions can be implemented as [Custom Data Processors in Python](https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Custom-Data-Processors-in-Python) enabled to be run automatically on import, paired with auto-import or auto-sync they allow complete automation.
