### ISSUE TITLE
User defined metrics in sidebar charts

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2230]
Hi,

I am using GC 3.4 on Linux and it seems that charts in the sidebar (trends view) are not saving user defined metrics. The metrics are removed completely when restarting the program. 

Creating a chart containing user defined metrics in the top bar, has no issues.

Kind regards,

Nigel

**Comment by liversedge** [comment]
Might be worth using the forums to discuss. Cannot recreate.

**Comment by nigelvdv** [comment]
Hi Mark,

I already mentioned this in the release candidate topic back in September. I think you were able to recreate it back then.  

[https://groups.google.com/d/msg/golden-cheetah-users/HOma_2lWyog/mKzpXr_JAAAJ](url)

A few posts below Manuel Oberti mentions the same behaviour.
No other user comments afterwards however.

Could it be that this was fixed in non-Linux builds, on which you perhaps tried to recreate the issue this time?

Kind regards,
Nigel

**Comment by amtriathlon** [comment]
I can recreate this issue adding the sample custom metric to an empty LTM chart created on the sidebar, the cause seems to be an initialization order problem: the presets for the first athlete in the session are loaded before custom metrics are added to the metric factory.
The problem doesn't happen for the next athlete opened in the same session since custom metrics are already initialized.
