### ISSUE TITLE
Deprecate QTKit and VLC support in favour of QT Multimedia

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#2242]
Need to build using AV Foundation from 10.12 onwards.

**Comment by liversedge** [comment]
see this for guidance: https://developer.apple.com/library/content/technotes/tn2300/_index.html

**Comment by liversedge** [comment]
should consider using qt video for mac builds from now on. the qt video support in recent qt5 releases is quite stable.

**Comment by Joern-R** [comment]
If QT video is working we should also remove the VLC player from the Windows builds. We are still on VLC 2.xx - while the recent builds are VLC 3.xx. I did a attempt to use VLC 3.xx, but the API has been changed in incompatible way. So additional changes would be necessary to adopt. (Not sure how many - stopped digging deeper when facing the problem). This would simplify the deployment / installer as well by removing another dependency.

**Comment by liversedge** [comment]
OK. I agree. Lets deprecate VLC and QTKit and adopt Qt Video. Will change title.

**Comment by amtriathlon** [comment]
On Linux also we are still on VLC 2.xx and it should be great to have one dependency less.
Only caveat is the functionality currently available depending on VLC:

- videosync (Windows and Linux)
- video overlays (Windows only)

**Comment by liversedge** [comment]
Probably just deprecate the overlays, they're a bit odd (xml config. no tooling).

**Comment by Joern-R** [comment]
Just had a look at the code responsible for RLV/videosync (and what libvlc functions are used). At least in QT 5.14. I could find similar function in the QMediaPlayer class. Since I have some RLVs from Tacx here I will try to adjust the code so that also QMediaPlayer can be used with RLV. If this works we can deprecated VLC. If not we need to decide if the function itself shall be deprecated. Ok ?

**Comment by amtriathlon** [comment]
Some ideas from @vlcvboyer in #1675 to implement video sync on Qt5 video, for future reference:

> Seems easy by using mp->setPlaybackRate(qreal rate)
> in VideoWindow.cpp:374 by adding, "GC_VIDEO_QT5" to "#ifdef GC_VIDEO_VLC"
> and then separate libvlc and QT with #ifdef at the few locations where it is used:
> 
> 436:libvlc_media_player_set_time(mp, (libvlc_time_t) (rfp.secs_1000.0));
> by adding for QT5 something like:
> mp->setPosition(rfp.secs_1000);
> 
> 442:libvlc_media_player_set_pause(mp, (rate < 0.01));
> by adding for QT5 something like:
> if (rate < 0.01)
> // maybe use mp->pause()
> // but preferably:
> mp->setPlaybackRate(0.0)
> 
> 447:libvlc_media_player_set_rate(mp, rate );
> by adding for QT5 something like:
> mp->setPlaybackRate(rate)
> ...
> 
> I'll not do the modifications as I cannot test on OSX on my side...

Preliminary tests by @Joern-R indicate the performance is poor compared with VLC, but lets hope it improves in future Qt versions.

**Comment by amtriathlon** [comment]
I am closing this since migration to VLC 3 is complete for Windows and Linux ci-builds, and it is enabled for macOS ci-builds with videosync functionality working in the same way in all 3 platforms. VLC 3.0.8 is included in all v3.6 installers.

Overlay widgets have some limitations on scrolling due to window manager interaction on Linux and they don't work on macOS, so they are enabled on Windows and Linux only.
