### ISSUE TITLE
libgcc_s_seh-1.dll is missing - after choosing "View --> Reset Layout"

### ISSUE THREAD

**Issue by sachale84** [GoldenCheetah/GoldenCheetah#2247]
Hi,
I got the following error "The program can't start because the libgcc_s_seh-1,dll is missing from your computer. Try reinstalling the program to fix this problem" when from Train I click on View->Reset Layout.
After several clicks on the "OK" the default train layout opens, but i believe this is not the proper way.

I'm using GC 3.4 64-bit on Win 7 64-bit.
Already tried the uninstall/reinstall and the issue always appear at that same point.

thanks in advance
ale

**Comment by Joern-R** [comment]
In 3.4 we moved from GCC compiler to MSVC - so that library is not used any more. Something has to be wrong with your installation. Please carefully uninstall - check your installation directory if it isreally clean and install the version provided through GitHub download.

Any further problems - please use the user forum: https://groups.google.com/forum/?hl=de#!forum/golden-cheetah-users

**Comment by sachale84** [comment]
Hi Joern, thanks for the quick feedback.
I've tried again with uninstall (+ deleting all related folders in C:\Programs but also %AppData%) but still the issue was there.

Fyi the only way I found to fix it is by removing the Video Player from the Train window. I've tried by removing all the other chart, one afther the other, and only the Video Player is causing that error message.
thanks

**Comment by Joern-R** [comment]
Hi Ale,

it looks that you are right (sorry for not noticing first hand). I re-checked all dependencies - the .dll is part of the VLC player which we embeed, but not part of the installer. This may be the cause of your problem. Can you please copy the .dll from the attached .ZIP file to the directory where GC is installed and re-test the Video Player.

[libgcc_s_seh-1.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/644622/libgcc_s_seh-1.zip)

Crazy thing is that the .dll dependency checker I use (which was fully reliable until now) does not show this dependency.

Thanks for your support.
Joern

**Comment by sachale84** [comment]
Yup! It's working fine now!
Thanks a lot
ale

**Comment by Joern-R** [comment]
For other users reading this - I added a Patch-01 - Installer to the release containing and installing the missing file to the GoldenCheetah directory. Not everybody may need it, since the file is used in many application build with MingGW. 

Thanks Ale for reporting and the more detailed investigation on this.
