### ISSUE TITLE
Allow import weight from CSV into activities

### ISSUE THREAD

**Issue by krzysiek-b** [GoldenCheetah/GoldenCheetah#2284]
I've got a CSV file exported from a mobile app i use to track my weight. I would like to import that file into all activities to monitor the impact of weight on my performance. The file contains two columns and a header. First column has the date and time. The second has numeric (float) value of measured weight in KG. I expect the weight to be set for all activities which for the date for the weight measurment is matched with the activity date (the time when the weight measurement was taken is not important to me).

I'm a programmer, so if I missed some option that enables to write a small script to do that please let me know. I wll do it myself and contribute if this will have any value for you :)

**Comment by amtriathlon** [comment]
GC already downloads weight data from Withings site, if you have your Withings account linked to GC you could upload your file there and then use GC download, otherwise probably the simple way is to write a script to convert the file to withings.json in the athlete's cache folder and restart GC, the format is documented here: http://oauth.withings.com/api/doc#api-Measure-get_measure and code handling it in GC is this: https://github.com/GoldenCheetah/GoldenCheetah/blob/1a19fa46fe1bfe3daa809314f7d9dca39081aba8/src/Cloud/WithingsParser.y
If you follow the last route please upload your script.
Cheers, Ale.

**Comment by Joern-R** [comment]
FYI - I started working on generalizing the current Withings Upload into "Body Measures" upload. Starting with Withings and Today's Plan as data source. I am also considering adding a CSV file import to this. (Just to avoid double work). Plan is to get this into 3.5 (if I find the time)

**Comment by amtriathlon** [comment]
Jörn implemented thin in https://github.com/GoldenCheetah/GoldenCheetah/commit/e39320012e156f2ab65ee5cd51a72f26fc6c6d28
