### ISSUE TITLE
Sync full profile data to Google Drive\Dropbox\etc

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2355]
Now there is synchronisation with external space only for activities. If i want to have my profile on different computers I have to also copy profile info (lth, ftp info and so on).

Could you add possibility to synchronise not only list of activities but also profile info? So users can easily open their complete profile on other computer.

Synchronise may be not all data (bak, cache, etc.), but enough to open profile on the other system.

**Comment by Joern-R** [comment]
Most of the profile data is stored in your athlete directory in plain .ini files since a few releases. You can sync those folders with "standard" techniques provided by the different cloud storage vendors. There is only one file "outside" the athletedirectory which contains infos like:

- the athlete directory path
- color settings
- directory names (e.g. last import dir)
- window geometries

trying to contain only infos which are specific to the machine you are running GC on (and settings which may cause problems if you move them between machines with e.g. different OS).

This file is stored at the "QSettings::UserScope" location - which depends on your OS. Locations are described here: http://doc.qt.io/qt-5/qsettings.html 

IMHO GC would not be able to provide additional value w.r.t additional functionality than simple file copy - which any other tool can do (probably even better).

If this does not cover you use-case please share more details why native file sync. function are not sufficient (use cases).

**Comment by freekode** [comment]
You are right. I tried sync activities and config folders from profile directory and it works good, but not perfect.
One problem I described #2388.
And another is - when new activity added to activities folder manually (by user, or due to syncing process), it doesn't show in the application on the first start (after add), I need restart the program, then new activity shows. Unfortunately not sure about that problem, will create ticket when reproduce it.
