### ISSUE TITLE
GC 3.4 crash when exporting to KML

### ISSUE THREAD

**Issue by Doorshifter** [GoldenCheetah/GoldenCheetah#2370]
Attached zip file contains a GPX file that can be imported but not exported to KML without GC crashing.
[7313348410858049_1.gpx.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/810062/7313348410858049_1.gpx.zip)
[Crash KML.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/810064/Crash.KML.txt)

**Comment by Joern-R** [comment]
I checked the file - the .GPX file does not provide a start date. So it's created by GC. Can you please send add the .json file created in the /activities folder of your athlete data. I crash happens when handling date/times. 

Interestingly import and export to KML works - which could be because of my timezone UTC +1. So your timezone would also be of interest.

Thanks.
Joern

**Comment by Doorshifter** [comment]
there are a few sites involved to generate this gpx.
source       http://www.bikely.com/maps/bike-path/t1956-46-majorca-tour-i-orient-es-37km

and then

conversion      http://gotoes.org/strava/Add_Timestamps_To_GPX.php

So this might not be a 'normal' gpx as you would expect from a (Garmin) device.

I am playing around with some of the Tacx RLV's I own to convert them to erg format which enables power over time training with 'distraction'. GC doesn't support 'over time' on a Mac only 'over distance' without speed control of the video. 

[2017_03_01_18_00_54.json.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/811730/2017_03_01_18_00_54.json.zip)

**Comment by Joern-R** [comment]
I imported the .json to GC - and exported as .kml - no problem on my windows installation (latest commit). So not sure if it's Qt / Mac / or any correctio which was done since 3.4

Plan is to publish a development build for 3.4.1 next weekend - I might be worth to check if the problem persists. I am not testing/building on Mac - so hard to help if it's a platform issue. 

Please check with the new build and report back the result (before we invest into any detailed analysis).

**Comment by Doorshifter** [comment]
Ok. Thanks so far. 

Gr. M

**Comment by Doorshifter** [comment]
checked this issue with the latest dev build (1703). GC still crashes. followed 2 scenarios with son and gpx files: change the date to today's date while importing, and no change, adopting whatever date (format is in the file). irrespective of the date manipulation (or not) GC crashed. two of the crash reports (change date scenario) attached.
[Crash export to kml after import json.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/823824/Crash.export.to.kml.after.import.json.txt)
[Crash export to kml after import gpx.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/823825/Crash.export.to.kml.after.import.gpx.txt)

**Comment by Joern-R** [comment]
Thanks - I looked at the dump - but cannot associate it to any obvious line of code which may cause the problem. And as mentioned before - I am building on Windows (not Mac). So I withdraw my assignment. Sorry.
