### ISSUE TITLE
GC 3.5 Overview replacing Summary

### ISSUE THREAD

**Issue by rrooster** [GoldenCheetah/GoldenCheetah#2378]
Hard to see @ mo how Overview replaces Summary — the hard data displayed in Summary for HR Zones, Power Zones, W'bal Zones, Intervals, etc. is valuable... The Overview dashboard as I see it @the mo, really doesn't give any of that granularity, it just provides... an Overview.

**Comment by liversedge** [comment]
Please don't open issues to make comments, the forum is the right place for that. There is an issue open for the summary rewrite if you must comment here: #1305 

Also, please bear in mind the overview is a WIP and the summary WILL be deprecated, since there are unsupportable technical issues related to QtWebEngine.
