### ISSUE TITLE
Strava Integration No Longer Supports Selecting Data Sets or Title

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2507]
Up to and including v3.5_DEV1703 it was possible to select the data series that got uploaded to Strava. This is extremely useful as it enables one to strip out things that some people prefer not to share, e.g. power data and heart rate.

This functionality went missing in v3.5_DEV1704 along with the ability to set a title for the activity. I know this is probably the result of #2414 but I wanted to highlight the issue now to ensure it's on the radar for 3.5 as would be a serious loss of functionality imho and I can't see an issue relating to this specific problem.

![screen shot 2017-05-04 at 12 33 02](https://cloud.githubusercontent.com/assets/804578/25702053/10b5a112-30c7-11e7-813e-32a9f5181e43.png)

**Comment by stschake** [comment]
You can now choose the activity tag that is used as a title in the cloud setup, e.g. setting it to "Workout Code" will make the activity show up on Strava with the GC Workout Code as title. That enables GC to automatically synchronise instead of having to prompt for a title each time.

You're right on the data series selection, that is a regression. Unfortunately this was hardcoded functionality in the old Strava share support, with many more cloud services now available it would be good to have a generic implementation here.

**Comment by arunh** [comment]
Good to know on the title, but I think the data series selection is quite a big deal - can it make the 3.5 milestone?

**Comment by liversedge** [comment]
I've already committed to adding that back. Its in the main refactor issue #2414 under regressions.
