### ISSUE TITLE
HRV support

### ISSUE THREAD

**Issue by ninardos** [GoldenCheetah/GoldenCheetah#2522]
As a commited athlete I want to track recovery status, which state of the art is done by HRV measurements.
Integration of the most frequently used apps (EliteHRV, ithlete) or direct data upload from compatible devices (RR-Intervals) would be good.
Tracking should include daily summary, detailed analysis of single readings, trends.

**Comment by ninardos** [comment]
Will HRV tracking be available in GC in the near future (next release perhaps)?
Basic functions should be very easy to implement.

**Comment by liversedge** [comment]
HRV metrics and data are now supported in v3.5 - a dev release is  available on the GC website.

**Comment by ninardos** [comment]
Any plans for integration of the above mentioned apps?

**Comment by liversedge** [comment]
Direct integration of R-R data is already supported. 
Ale is looking at how HRV data can be incorporated into measurements.

**Comment by ninardos** [comment]
I understand that GC 3.5 does support HRV (R-R), but can´t figure out how. I can set up a data field, and I do have a Garmin Edge 1000 with Garmin Premium HR Strap. Still GC does not show R-R values. Any hints on what I am missing / doing wrong?

**Comment by ninardos** [comment]
Then additionally: I do measure HRV in an APP, Elite HRV, from which I can export the data. Data is raw text with a single row giving R-R in ms.
I can´t figure out how to include this in GC as a "Morning Reading" type workout. Can this be done? And how?

**Comment by ninardos** [comment]
Alternatively: is there a way to connect to EliteHRV directly and import data from there in GC?

**Comment by liversedge** [comment]
Please use forums for help requests (but garmin unlikely to be recording R-R values).
We are planning on adding import from hrv apps but its not available right now sadly.

**Comment by ninardos** [comment]
Thanks, will try to find the right forum.
Does "planning on adding import" mean this will likely be in the next release (December)?

**Comment by rgeorge1985** [comment]
Hi Ale.
Just chiming in. Giving the user import ability to gather data from an ascii or .csv file would be very handy for plots. I'm going to take a guess than 95% of the people who know anything about HRV are monitoring metrics after waking up. There's too much noise and artifacts for HRV in sports activity data to mislead the user and personally it's not useful to me because it's not data taken under a 'controlled' condition. 

Plots that would be useful - time trends of rMSSD, LNrMSSD, LNrMSSD/AVNN. For just these three, there can be option to view acute signals or chronic signals based on a 7 day moving average. The latter is more useful.

**Comment by amtriathlon** [comment]
Ron, CSV import is planned, also the integration with existing HRV metrics so, if you have data taken in controlled conditions you can use the HRV metrics computed on this data to set HRV measures. See https://github.com/GoldenCheetah/GoldenCheetah/issues/2568
