### ISSUE TITLE
Import Tacx Real Life Video or Ergo Video fails?

### ISSUE THREAD

**Issue by stewfelstead** [GoldenCheetah/GoldenCheetah#2526]
I've install version 3.4 on MacOS and have tried to import various Tacx video's (avi format) into GoldenCheetah. Whilst the .rlv files import the corresponding video files don't. I converted one of the avi's to mp4 and that imported but wasn't in anyway linked to the .rlv file.

I may be misunderstanding the video feature, but I was hoping the I could use GoldenCheetah in a similar way to Tacx Fortius and just ride the videos and the workload required would be driven by a combination of speed and gradient.

Have I missed the point, or is that not the intention of being able to upload video?

**Comment by vlcvboyer** [comment]
Hi,
Unfortunately MacOSX uses QT for video instead of VLC (windows and Linux build). At present video synchronisation is only available for VLC (tested on windows build ; to be tested/adjusted/validated on Linux).
Please see FeatureRequest #1675 where I've explained quickly what to do but I don't have any Mac platform with me for testing.

For windows users (or Mac users when it will be part of GC OSX build):
In order to use Video Sync train, you have to select 3 files on the left panel in order to have the full functionalities:
pgmf for gradient synchronised relative to distance;
rlv for video synchronisation relative to distance;
avi for video;

I still have to capture a video to be used as a tutorial...

Linux build uses VLC; video synchronisation should work in theory but needs to be tested and validated

**Comment by stewfelstead** [comment]
Thanks for the detailed reply.

I have a couple of observations that may be useful in improving the feature.

1. I have a collection of Tacx Real Life Video and haven't been able to import any of them into GoldenCheetah. However if I convert them to MP4 they import fine. Although I don't know if they will work due to point 2 below.

2. What's a pgmf file and where would I get them from for my Tacx videos? Can I extract them from the avi or rlv files?

Looking forward to your response....

**Comment by vlcvboyer** [comment]
1. Take care of copyright and licence when considering Tacx Real Life Video. Please read carefully the restrictions and ensure that you are allowed to read the files with an alternative software than Tacx's one.

Note: There are a lot of RLV available for free on internet. 

2. Normally you should be able to play video in any case (just choose the video and do not select RLV or PGMF file)

The 2 other features depends on the files available and describing the workout (rlv and pgmf) but also your system as mentioned in my previous post.

RLV file is for synchronisation between video and distance/speed (basically it says that km 12.236  is frame 56875 of the video, etc.)
PGMF file is for synchronisation between trainer brake and distance/speed (basically it says that km 12.236 gradient is 1.64%, etc)

If you do not own a Real Life Video set including RLV and PGMF in addition to AVI it will not be usable in GC. There are some softwares which allow conversion from GPX to PGMF and RLV (typically for your own shoots) but you need the GPX file associated to the video !

**Comment by stewfelstead** [comment]
Thanks. Do you have any links to the free rlv sources?

**Comment by vlcvboyer** [comment]
Please check the term of service / licence type as it change regularly...
Typical free RLV sources:
http://www.route4u.dk/index.php/rlv
http://cyclingrlv.com/
http://rlv-stormarn.de/

**Comment by Joern-R** [comment]
I consider this discussion completed - the open topic of RLV on MaxOS is tracked in a separate Issue. Therefore closed.
