### ISSUE TITLE
Polarized Zones Enhancements

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2555]
Add Aerobic Threshold HR/Power/Pace to Zones to allow personalization.
Add Time in Polarized Zones metrics

**Comment by batsonjay** [comment]
I *think* this is what your issue says, but for the record, I'm going to expand on a portion of this just a bit. (This discussion is not comprehensive, IMO.)

Polarized training reduces the number of Heartrate zones to 3, and uses different zone names. See https://www.researchgate.net/publication/46403553_What_is_Best_Practice_for_Training_Intensity_and_Duration_Distribution_in_Endurance_Athletes

While GC preferences permits deletion of individual heart rate zones, it does not permit renaming of the remaining zones to properly match the common nomenclature used for polarized zone training. For instance, if I delete Zones 4 & 5 in the zones tab, the remaining zones are named "Active recovery, endurance, and tempo"; the latter is particularly misleading in the polarized training model.

So:
As a user I want to be able to name the Heartrate zones in an athlete profile so that observing / tracking time-in-zone can use the "correct" zone name.

**Comment by amtriathlon** [comment]
@batsonjay: no, what you report is not related to this issue. You can use 3 zones and rename them but you must do so in Default tab, see https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Athlete_Training-Zones#zonesdefault-tab

**Comment by amtriathlon** [comment]
This article is good a remainder about the need to include AeT as an explicit parameter: https://www.endureiq.com/blog/easy-should-be-easy

**Comment by amtriathlon** [comment]
The core of this issue is implemented in master:

1. Aerobic Threshold (AeT) HR/Power/Pace are now configurable in HR/Power/Pace zones, similar to LTHR/CP/CV.
2. They are used to delimit Polarized Zones I and II in histogram charts.
3. The user can set them to estimates from lab or field test or left them unset (value 0) so they default to the same values used before in charts.
4. They can be used in formulas via: config(aethr), config(aetp) and config(aetv)
5. They are also available in Pyhton, R and Rest APIs

My original intention was to add built in metrics for times and percentages in each of the 3 zones for each series (18 new metrics), but now we can add them as user metrics uploaded to CloudBD so interested users can download them. There is a trade off between convenience vs to increase memory footprint for all users, even those not using them.
I am not sure which is the best solution, what do you think @liversedge ?

**Comment by liversedge** [comment]
Builtins are best, but we can add them later, no rush !
