### ISSUE TITLE
Calories (HR) calculation

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2584]
Hi,

Calories based on HR don't seem to be calculated correctly in the latest dev build. The standard "Calories (HR)" metric just gives a "0" output it seems. Sex, Age and Heart Rate data are present for the activity. 

I created a custom formula that does seem to work:
`{` 
`value {`

`if (Sex="Male"){
((-55.0969 + (0.6309 * Average_Heart_Rate ) + (0.1988 * Athlete_Weight ) + (0.2017 * Age ))/4.184) * Duration/60;}`

`else if (Sex="Female"){
((-20.4022 + (0.4472 * Average_Heart_Rate ) + (0.1263 * Athlete_Weight ) + (0.074 * Age ))/4.184) * Duration/60;}`

`}`
`}`

I checked the metric in the source code over here:

[https://github.com/GoldenCheetah/GoldenCheetah/commit/930a33585592b9a25d87f058ecaac7c27c15cb29](url)

I see some differences between the names of the metrics in the source code and the names of the metrics I'm using in the custom formula (e.g. "average_hr" in source code versus "Average_Heart_Rate" in the custom formula). Could this be a reason why the standard "Calories (HR)" metric gives "0"?

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
It's working for me using both the last development build and current master.
Builtin metrics use the metric Symbol which is not always equal to metric Name.

**Comment by michaelprager** [comment]
I had the same problem, calories would always display as 0. Using a debugger I was able to find the reason for this: my age was calculated as -62. For some reason, my birthday had the wrong century set (2000 instead of 1900). Not sure if this was a typo from my side or some kind of update issue. Anyway after setting the correct birth date, the calories metric works fine.
