### ISSUE TITLE
No Danniels points in running activities

### ISSUE THREAD

**Issue by jmrius** [GoldenCheetah/GoldenCheetah#2681]
I get Danniels points in cycling activities, but not in running ones.

GC version = 3.5 DEV1710

**Comment by grauser** [comment]
Currently Daniels Points in GC are adapted for cycling using power (instead of pace for runner in the original Daniels Points) and standardized to 100 points for one hour at CP like BikeScore or TSS (instead of 33 in original).
Now GC is for runner too. Perhaps could we have both. 

In 2009 @srhea, after adding this metric, proposed to rename it "Daniels Hundreds" (https://groups.google.com/d/msg/golden-cheetah-users/SpL_zfkLvPc/goyC1QsNiTwJ)

**Comment by Walibu** [comment]
I am interested as well in the same function. As a short distance triathlet I prefere DanielPoints for cycling and for running/swimming I set them manually according my feeling.

Today I was looking through the code of src/Metrics/DanielsPoints.cpp. And it looks quite easy the add the Danielpoints for CS (Critical Speed) like it is done for CP, if sport is set to "Run" (item->isRun)

A point to think about is: if somebody uses a powermeter for running like stryd, see:
https://www.dcrainmaker.com/2015/01/stryd-first-running.html
A solution would be, just check the running activity, if there are raisonable powervalues saved, use power for daniel points, which is more accurate than speed if running in hilly enviroment. Or let the user choose. But easier to implement is, use power if we have it.

An other not easy task would be, if we want to adjust the speed according ascending/descending, like in Strava they have a function for that.

First I would try to implement it, without speed adjust. Just take the current speed and filter it perhaps like a 10 sec rolling average, that peaks do not count and then use CS like (->getCV(item->paceZoneRange)) instead of Critical Power CP.

**Comment by amtriathlon** [comment]
If you want speed adjust considering changes in potential and kinetic energy you could use the xPace metric instead of average pace

**Comment by Walibu** [comment]
Thank you for that hint, I see you have written a lot about that in Govss.cpp and Coggan.cpp.

A question:
Is xPace not similar to xPower which is Normalized Power and for running xPace would be the Normalized Pace?

In Govss.cpp I see the function running_power() which looks like calculating RunningPower according the slope and runners weight/height which would be very useful.
But instead of power I would like to have an adjusted speed according the slope, higher if running upwards and lower than the current speed if running downwards.
Like GAP in Strava (Grade Adjusted Pace)

**Comment by amtriathlon** [comment]
Yes, xPace is like xPower: the pace which sustained on flat terrain would give the same GOVSS score.

**Comment by Walibu** [comment]
Hi
I implemented a version with DanielPoints for running and using the following GAP from Strava to adjust the speed according the slope (Gradient in %)
![gap_adjusting](https://user-images.githubusercontent.com/3055774/35766443-18bdfbbc-08d9-11e8-9b4b-4e6a68253875.png)
https://medium.com/strava-engineering/an-improved-gap-model-8b07ae8886c3


I averaged the speed over a window of 10 secs for the DanielPoints calculation, which is sufficient for my recordings of SuuntoAmbit2 watch.
Generally it fits good and gives reliable values including hill repeats from 30 secs to 1 min.

Now I am testing with different Runs and Rides. According my feeling cycling feels a bit harder with same Daniels EqP than running. Maybe I need to check my CP (FTP) and CV values.
