### ISSUE TITLE
Freezes on laptop when using dedicated GPU (3.1.5)

### ISSUE THREAD

**Issue by arnaudf73** [GoldenCheetah/GoldenCheetah#2730]
Hi everyone.

I recently bought a laptop and decided to install GoldenCheetah on it. I quickly encountered freezes while switching between trends and rides screens. 

First of all my config (Acer Aspire 5 A515-51G-526Y) : 
- Intel Core i5-7200U + integrated graphic chipset Intel HD620
- 4GB of RAM
- GeForce 940MX GPU (2GB)
- Windows 10

For instance : I select an activity, go the rides screens, then into details and when I select metrics nothing happens. The software freezes and I can't select anything else in the rides screen, unless I go to trends, then back to rides. The rides>details>metrics screen is displayed but the problem appears again if I try to select another screen in rides>details.

I decided to go back to 3.1.4 and it works perfectly. 
I tried to install the 3.1.5 32 bits version or adjust compatibility settings but it did nothing.

I then noticed that the GeForce 940MX was being used to display GoldenCheetah, so I decided to force the use of the integrated graphics chipset and the problem disappeared.

Anyone has ever head of that behaviour?

**Comment by Joern-R** [comment]
We had one issue with a dedicated GPU in a laptop. Please set the enviroment variable:

QT_OPENGL=software

This makes QT doing pure software rendering an not relying on the graphics driver.

Other options you may want to try (and please let us know the results):

QT_OPENGL=desktop
QT_OPENGL=angle

Would be interested to understand what works / what not to be able to help other users.

Cheers.
Joern

**Comment by arnaudf73** [comment]
Hi, thanks for your help.

I just tried it and here's the results : 
- QT_OPENGL= software => OK
- QT_OPENGL= desktop => KO
- QT_OPENGL=angle => OK

**Comment by Joern-R** [comment]
@arnaudf73  thanks a lot for the evaluation and feedback.

So please use one of the settings which works for you. It seems to be a problem of the OpenGL drivers or your laptop. 

The setting "software" completely "skips" the OpenGL drivers, the setting"angle" maps the OpenGL calls to DirectX calls - so that also no OpenGL driver is used.

Since for most of the users the default setting of the software works - which ideally should find the proper setting itself (not always the case as we learn) - we plan not to change this to a default set by GoldenCheetah (by now).
