### ISSUE TITLE
Slope in RLV mode: Resistance change is ahead of video

### ISSUE THREAD

**Issue by huschauer** [GoldenCheetah/GoldenCheetah#2817]
I am a new user to the train mode and used RLV for 4 runs now. The machine and GC emulate slope well. I feel a delay between change in slope and the video. I feel the hill incline before I get to the base of the hill. Also it becomes easier and downhill like resistance before reaching top. I am talking of up to 1 minute offset within a 1 hour ride. I know the PGMF and RLV data are ok, because I had used the same on Tacx software in the past and they were spot on. I had read, that some users feel the resistance changes being delayed. However, this is vice versa. Video lags behind resistance change.

**Comment by liversedge** [comment]
which version of GC are you using?

**Comment by huschauer** [comment]
running latest stable 3.4 version for Windows downloaded from website

**Comment by peterbrant14** [comment]
I've also found this and have been doing some investigation. It seems to be a cumulative effect. The further into the RLV you are, the greater the mismatch between slope and video. It seems worse on videos that have lots of transitions between filming speeds. I think the issue is with the way that the distance between sync points is calculated when there is a speed transition. I have a fix that I am testing at the moment and I could raise a PR for it when its ready (hopefully in the next few days).
