### ISSUE TITLE
2018 DEV versions fail to launch in WIN10

### ISSUE THREAD

**Issue by oldjiberjaber** [GoldenCheetah/GoldenCheetah#2855]
GoldenCheetah_v3.5-DEV1804_64bit_Windows.exe
& GoldenCheetah_v3.5-DEV1802_64bit_Windows.exe
Windows 10

Both versions fail to run after installation, reverting to GoldenCheetah_v3.5-DEV1710_64bit_Windows.exe works.

I've tried removing every version of the Visual C++ and also R but to no avail, if I double click to launch I do not even get the progress % 

There must be something I am missing but I have not been able to find using a google search?

**Comment by ragman1976** [comment]
Same issue here (Windows7)

**Comment by liversedge** [comment]
Make sure you haven't got it blocked by windows firewall or using wrong c++ redist as per the readme.

**Comment by Joern-R** [comment]
Which Windows Version exactly - one way to find out is running "winver.exe". We tested on several Windows machines (especially "clean" ones without any development tools).  Recenct Win 10 Version 1709. GC started. The change from 17xx to 18xx version was the move to a new Qt Version (5.9.3) instead of 5.8.0. I even uninstalled the 2015 redist - and the software still worked, since the DLLs seem to be part of standard Win 10 delivery as well. (Will move to Win10 1803 soon for testing).

**Comment by ragman1976** [comment]
Same issue here. Since 1802 GC doesn`t start (error massage attached). With 1710 everything works fine.
I deinstalled R and C++ completely and tried it again, no success.

If you need more information let me know.

![start](https://user-images.githubusercontent.com/8372310/39560480-a915cb62-4e9e-11e8-8589-0bad0becf1af.PNG)
![win](https://user-images.githubusercontent.com/8372310/39560481-a93463c4-4e9e-11e8-97d3-d889c2478826.PNG)

**Comment by oldjiberjaber** [comment]
Current version is Win10 16299.371
I've no idea what service pack was on back when I tried the Feb release.

Is there a command line for GC to show debug or a log I can provide to help ?
How can I help you further?

**Comment by Joern-R** [comment]
Win 10 Version is one patch behind on recent 1709 release - but that should not be an issue. 
Win 7 Version is SP1 - there are newer formal version, but I assume all patches provided by Microsoft are applied.

We have > 1000 downloads of the Windows Versions and not a significant number of reports of this problem (besides you + some might not have reported). All developers do not face the problem on Windows (also testing on other PCs which do not have any dev. stuff installed).

The provided version is not a debug version,... - what you could try is to have a look at the Event Log. 

https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

There may be a bit more information on where the problem occurs, giving hints for further investigation. Not sure if Qt / Windows / ... logs anything. But at least worth to check.

Thanks.
Joern

**Comment by oldjiberjaber** [comment]
Thanks Joern - will try and take a look mid-week and report back

**Comment by ragman1976** [comment]
Good morning everybody,

I´ve started GC and the error massage occured as alwasy since 18xx release. The eventviewer shows the attached massage. If you need more information please let me know.

![vienviewergc](https://user-images.githubusercontent.com/8372310/39685339-45717396-51c2-11e8-9100-b3a5fed3df42.PNG)

**Comment by Joern-R** [comment]
Thanks - just checked my PC. The version of the mentioned .DLL is higher / installed in february. See here: 
![image](https://user-images.githubusercontent.com/7491731/39687809-472524a4-51d0-11e8-97f2-c1acbc52d9d4.png) 

My Win10 Version is still 1709 - but will upgraded to 1803 today. Google does show a number of hits when searching for the .DLL, but nothing obvious in context of Qt Applications - so - first ask would be to upgrade to the latest version/patch level and test again. 

Thanks Joern

**Comment by Joern-R** [comment]
FYI - Upgrade to most recent Windows Version 1803 is completed (64Bit). No problem w.r.t. to GoldenCheetah starting. The "ucrtbase.dll" mentioned above is contained a new version with 1803.

**Comment by elShambler** [comment]
I was having an issue running mine as well. I'm not sure if this will help, but worth a shot. The Python Tools were enabled by default, but with no Python library attached (maybe because I use Anaconda for my main python dist), so I had to start GC from the cl with the following options:

``GoldenCheetah.exe --no-python

From there I could configure my libraries and get it running again.

**Comment by AirVetra** [comment]
@elShambler Thanks, it worked great for me!!!

**Comment by ragman1976** [comment]
Worked also great for me!

**Comment by oldjiberjaber** [comment]
Worked for me also - thanks!
