### ISSUE TITLE
Add a card with more possibilities to the guess power values function

### ISSUE THREAD

**Issue by IlGehring** [GoldenCheetah/GoldenCheetah#2912]
Add more possibilities to the guess power funktion to insert the defoult settings like on following page

http://infotom.de/kreuzotter/

**Comment by amtriathlon** [comment]
Current parameters are enough for the used model, kreuzotter website allows the very same inputs, the difference is they have predefined CdA&Crr values for some, supposedly typical, cases.
While this obviously makes this tool easier to use.
I don’t think it is a good option here since, hiding complexity relieves the user from the burden to understand the used model, but also its limitations which are far more than new users without power meters tend to recognize bringing a false sense of accuracy.
