### ISSUE TITLE
Todays Plan sync not working

### ISSUE THREAD

**Issue by secrettrainer** [GoldenCheetah/GoldenCheetah#2944]
Hi,
Can no longer authorize Todays Plan / golden Cheetah, get error message

Error retrieving access token, Socket operation timed out (4)

**Comment by liversedge** [comment]
when did this start happenning?
TP servers may be down for maintenance.

**Comment by secrettrainer** [comment]
Happened yesterday. Just tried again.

**Comment by Joern-R** [comment]
I just tested the connection - both "Authorization" process as well as synchronization (Download from TodaysPlan) work fine for me. Win64Bit - 3.5Dev10

Please check and - if it fails - provide more details (version,...)

**Comment by Joern-R** [comment]
Ok thanks - nothing we can change / fix. So I close this message.

**Comment by secrettrainer** [comment]
Hi - can this be reopened?
Todaysplan issues have been fixed by GC authorisation still not working.

**Comment by Joern-R** [comment]
What exactly is not working ? 

I am synchronizing frequently - loading Activities from TodaysPlan as well as loading Workouts from Todays Plan. No issues over the last week (Win 10 - recent build).

**Comment by secrettrainer** [comment]
Hi,

If I initiate the sync I get the error 'unable to connect', in the details it says 'network problem reading todaysplan data'.

If I go into options to reset, after clicking on authorise, I can login into todaysplan ok and allow authorisation. When I 'allow' I get error 'error retrieving access token, socket operation timed out (4)', in details it has same message.

Cheers

**Comment by Joern-R** [comment]
Thanks for the details. To be honest - I have no idea where to look at / what to analyse in this case. 

One more question - Are you using a payed account or the free account. And (even if I do not think this causes the problem) can you please revoke the authorization of GoldenCheetah in the TodaysPlan App, then re-authorize via GoldenCheetah.

The error message indicates a network problem - so anything specific with your network / company/proxy/special firewalls?

And last idea - since we a using the same logic/code for all integration - do you have other synchronisations enabled (e.g. Strava) and are those working fine?

**Comment by secrettrainer** [comment]
Hi,

I've got a paid todaysplan account, and I've already done the revoke authorisation in todaysplan - made no difference.

My network is just a home ADSL, nothing has changed for a long time.

Also set up in GC to sync to Strava. Just tried that on a a ride, got a 'no connection' message. This has worked fine before, so maybe my network - but no idea where to look/start.

No problems before updating to latest dev release.

**Comment by Joern-R** [comment]
Weird - as said - I am using the same basic setup. Strava/TP integration - Win10. Never ran into this. And we did not get any such feedback on the Google Mailing List.

Do you have access to another PC/Laptop where you could do a clean new-install of GoldenCheetah and just check if the problem occurs as well. Or (if its installed on a laptop) use some other Wireless Lan to test. (To eliminate some of the variables). 

Do you still remember which version you were running before moving to 3.5DEV10 ? I had a look at the commit history, but could not find any changes in this area sine June.

**Comment by secrettrainer** [comment]
Ok, just tried using phone/cellular wifi, no difference.

Can look at new install on different computer tomorrow.

**Comment by Joern-R** [comment]
Thanks - and sorry for the efforts.

**Comment by liversedge** [comment]
Might be worth checking the right url is being used ?

**Comment by secrettrainer** [comment]
Hi - how would I check URL?

Anyway, I have installed same dev version on different computer also on my home network, everything works fine. Have checked both installs have same preferences etc, no difference.
Also, deleted firewall settings on computer with original install to make sure no difference.

So, only difference now is Win10 build. The computer where sync not working is Win10 Pro, version1809, the computer where everything works is win10 home, version 1803.

Any ideas? The computer where sync is not working is my laptop, so is my preferred device.

**Comment by secrettrainer** [comment]
Ah, ok, URL ok.
Is it possible to test API call though?

**Comment by liversedge** [comment]
I wonder if GC is blocked internet access on the PC that doesn't work.

**Comment by secrettrainer** [comment]
I checked that firewall settings are same on both computers

**Comment by Joern-R** [comment]
It may relate to 1809 - I am actually using 1803 PRO which works. 

Just checked why I did not install that yet and found multiple articles on severe problems with 1809 - so that MS has stopped the rollout. I seem to be lucky that I did not get the update in the beginning (since I was on vacation that point in time).

If it's your private machine you may try to revert to 1803 - or wait for further patches.

As soon as 1809 is available again I will update and check the result.

**Comment by secrettrainer** [comment]
Hi,

For future reference I fixed this through doing an SFC scan - had a
missing/corrupt Windows file that probably related to build 1809.

Regards

**Comment by Joern-R** [comment]
Thanks a lot - very good to know. We have similar problems in User List for Strava,...  I will give the hint so the guys can run the scan.

Best regards.
Joern
