### ISSUE TITLE
Strava Sync not working in current build 3969 v3.5=DEV1901 on OS:Win

### ISSUE THREAD

**Issue by mike-rennie** [GoldenCheetah/GoldenCheetah#3011]
Hi, I'm running GC:

Build id: 3969
Version v3.5=DEV1901
OS: Win (Windows 10).

The Strava sync setup is unable to be completed. Each time it proceeds through the account login to the "Authorize Golden Cheetah to Connect to Strava" screen. Leaving all defaults ticked and clicking "Authorize" incessantly results in an "SSL Token Refresh Error" stating 'Error retrieving access token, Socket operation timed out (4).'

Is anyone able to advise a resolution for this issue?

Many thanks.

**Comment by Joern-R** [comment]
I just revoked my Access to GoldenCheetah in Strava and went through the authorization process without any problems. (Win 10 / DEV1901 / 64Bit). 

We had cases like this when the Strava,... Website had some issues / high load /...

Please try again.

Thanks.
Joern

**Comment by amtriathlon** [comment]
> I tried adding Strava manually (as described here), but still can't complete the setup.

Those instructions are for building from source, no need to follow them if you’re using an official build

**Comment by Joern-R** [comment]
Can you please check if you you have a Proxy Server configured for your Lan (found an Qt error message pointing in this direction). If yes, please de-activate the Proxy Server (if a proxy script or a manual server setting is active). And check again. (https://www.youtube.com/watch?v=jBWuRwHIhdY)

**Comment by Tupperware69** [comment]
Apologies for the delay.

No proxy server configured for me.


> > I tried adding Strava manually (as described here), but still can't complete the setup.
> 
> Those instructions are for building from source, no need to follow them if you’re using an official build

I tried to add golden_cheetah as authorised app directly in Strava, as suggested.  I didn't rebuild GC.

The sequence is as follows:
1. Share...->Add Cloud Account->Activities->Strava - service credentials window opens
2. Click on Authorise 
3. OAuth window for Strava login -> enter username/pass
4. Stava request to authorise GC -> click on Authorize (all checkboxes ticked)
5. Window changes to GC home page and error box pops up stating:
Error retrieving access token, Socket operation timed out (4)
6. Click Ok and I am back at step 2 (token not populated).

**Comment by Joern-R** [comment]
Please make sure to revert anything you have done under: https://github.com/GoldenCheetah/GoldenCheetah/wiki/Strava-configuration 

This is only intended if you build your own GoldenCheetah Version.

Before you try again, make sure to revoke the GoldenCheetah authorization in your Strava Account here: https://www.strava.com/settings/apps (if it exists).

Besides that I have actually no idea - I did un-authorize and re-authorize with 1901 on Windows twice to verify if I can reproduce - no issue on my installation.

**Comment by Tupperware69** [comment]
Thanks for the reply.  I already revoked the access for the GC strava app I created so it doesn't exist any more, so don't think that is the issue.

Is there any way to create the authorisation token manually and then add it to GC?

Is it worth trying to build GC myself and using the instructions linked?

**Comment by Joern-R** [comment]
Thanks for the link - I just installed 1901 in a Laptop where is has never been installed before and also QT was never installed (just to check that I did miss some .DLL in the installer). Unchanged behaviour - I was able to authorize my Strava Account and to download files. 

I am a bit out of ideas how and where to search. One more - can to try to authorize any of the other cloud services or drop box. (most of them should allow to register for a trial account if you don't have a regular one). I'd like to see if the problem is Strava specific or general.

Thanks in advance

**Comment by Tupperware69** [comment]
I attempted to add a Dropbox and Google Drive account but both failed with the same error.

I previously downloaded 3.4 but have uninstalled that already.  So I went ahead and uninstalled 3.5 DEV1901 and reinstalled it.  During the install, I get an error when installing the C++ redistributable - log extract below.

[064C:3518][2019-02-05T17:57:12]i052: Condition 'VersionNT64 >= v6.0 OR (VersionNT64 = v5.2 AND ServicePackLevel >= 1)' evaluates to true.
[064C:3518][2019-02-05T17:57:12]i199: Detect complete, result: 0x0
[064C:049C][2019-02-05T17:57:21]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

Can newer C++ runtime cause issues? The latest one I have installed is 2017 - 14.12.25810.

Anyway, after I reinstalled....it works!

Not sure what the problem was, I didn't change my C++ runtime or anything, just uninstalled/reinstalled (installer was not redownloaded even).

Thanks for your help.

**Comment by Joern-R** [comment]
Thanks for checking - I update the C++ runtime in the installer from time to time. Usually I use the version provided with the Qt library (but it seems I kept an older version in the 1901 installer). Having a newer version installed (so far) never created problems. But I will update the version packaged with the installer as well for the next build.

Good to hear that it works now. And we keep an eye on similar messages to see what we can do on our side. No real idea of the root cause - it's kind of "Did you switch it off and on again" effect.
