### ISSUE TITLE
L/R Power in Train Mode is reversed compared to a Garmin Fit file

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#3017]
using a P2M NG.  A recorded file with a Garmin Edge 520 shows always shift to the left:
![fit](https://user-images.githubusercontent.com/23431166/52534886-7592e580-2d47-11e9-83ed-4eac4c6e0cde.png)

Did a record with Golden Cheetah at the same time too and here the data is reversed:
![gc](https://user-images.githubusercontent.com/23431166/52534893-87748880-2d47-11e9-85da-665aa381bf5f.png)

**Comment by sleeponastar** [comment]
The same here.
Moreover, the values of L/R balance are different: 48.9-51.1% for GC and 51.8-48.2% for Garmin fit.
[Archive.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3029824/Archive.zip)

**Comment by sleeponastar** [comment]
Seems to have the same problem with reverse L/R power balance during activity import. Checked with FIT file from garmin connect

**Comment by Genussradler** [comment]
same with the favero assioma duo, gamin edge 1000 and the training mode of gc.
with the garmin edge I normally have a L/R balance around 48/52
in the gc training mode it's always around 52/48

**Comment by mondoshiwan** [comment]
with the faveros you could do a simple test - they measure the L/R Power independently, click out the right pedal and pedal only with the left leg a few seconds and do the same with the right leg. My guess is that the L/R channels in TrainMode are mixed up somewhere in the GoldenCheetah code, but i don't no if that is even possible.

Genussradler klingt so deutsch… :-) Grüße

**Comment by amtriathlon** [comment]
That would help to debug, if someone attach both files, the one recorded with GC Train and a Garmin FIT file from the same short activity with alternate single leg pedaling, I can give it a look.
Looking at distributions from large files may give a hint, but has not been conclusive.

**Comment by Genussradler** [comment]
attached is a zip file with two fit-files. 
one from gc training and the other from a garmin edge 1000. 
~30sec with both legs
~30sec right only leg
~30sec left only leg

it could also be a labeling issue in GC. instead of left/right-balance it should be right/left-balance?!
btw I'm using build 3991

[LRTest.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5777655/LRTest.zip)


and yes, I'm from germany ;)

**Comment by amtriathlon** [comment]
From ANT+ Specification:
![image](https://user-images.githubusercontent.com/1444784/103826072-e7b7f600-5054-11eb-80da-7e68dc85aec0.png)

ANT+ Message seems to be Ok:
https://github.com/GoldenCheetah/GoldenCheetah/blob/d50e1a8552b98a4e2545dbed3c7b9b08a4ac3de1/src/ANT/ANTMessage.cpp#L425

FIT Import has an error: when bit 7 is not '1' the result is undefined, not inverted:
https://github.com/GoldenCheetah/GoldenCheetah/blob/89d99ccecfd62f82adaeae96b0d65a8aad0b1f28/src/FileIO/FitRideFile.cpp#L1803

So, we need to fix the error in FIT import and change one of them (or both) for consistency.

Since we are at this, an additional problem is 0 being interpreted in Activity chart as "no data".
