### ISSUE TITLE
Loosing ant connection - tacx neo + garmin pulse meter

### ISSUE THREAD

**Issue by ebjordal** [GoldenCheetah/GoldenCheetah#3020]
After I connect pair with my heart meter and tacx neo I seem to get good readings from both. 
When I start an activity (in manual erg mode) I seem to get good readings and I am able to set power levels on the Tacx for about 5-10 seconds after start the activity. I noticed today that the power readings sometimes seem to refresh when i hit plus or minus to the power button, though it stopped reading after about 5 seconds again.

The ant dongle is located just infront of the neo with usb connection to my laptop.
My system is running Ubuntu mate 18 (LTS). 

I am a bit new to Golden cheetah, so I am abit uncertain whether there are logs or other I can attach to help sort out the connectivity issues. If so, just give me a tell and I will do my best to help. 

I noticed there was an email about a seemingly similar topic on mac, though I could not find the ticket here on github. 

Kind regards,
Erlend

**Comment by diggidude** [comment]
Hi Erland,
I have been using the Tacx Neo with TTS4 and ANT+ antenna and was not happy. The SW is kind of ugly. Then I tried GC 3.4 for the last few yeras. Just recently I changed to GC 3.5 because of dropped readings for speed and irrational high readings for cadence. It didn't change those problems. Funny is, my Garmin Edge 800 reads sensible data for speed but also has those erratic high values for cadence. 
There is more on https://groups.google.com/forum/#!searchin/golden-cheetah-users/tacx$20neo$20smart|sort:date/golden-cheetah-users/38_FThPJjyo/JkqmmB2DBQAJ
Regards
DD)

**Comment by charles-m-knox** [comment]
I am also having this problem. My official Garmin ANT+ USB stick works for about 2-4 minutes then drops off entirely, and I have to restart GoldenCheetah, unplug/plug in the USB stick again, and repeat the process ad nauseum. 

GoldenCheetah + ANT+ worked for about 2 weeks and now it's doing this. Any ideas on what's going on?

**Comment by amtriathlon** [comment]
This is similar to https://github.com/GoldenCheetah/GoldenCheetah/issues/2816 and it seems to have been solved by the change to libusb1.0 in v3.5 RC1.
