### ISSUE TITLE
Freezes when importing from Sporttracks.mobi

### ISSUE THREAD

**Issue by BigFriendlyDuck** [GoldenCheetah/GoldenCheetah#3134]
When importing from sporttracks.mobi, GC freezes at import of certain activities (about 9 % of a total of 140), and I has to force quit.
No sure, but my guess is that activities I have modified with the SP3 desktop app and than synced to SP.mobi is the culprits. Just a feeling, tough.

Is there a way to create error-logs in GC?

edit:
GC v3.5-DEV1903
DB Schema: 149
Metrics: 35
OS: Win 10, version 1809

**Comment by amtriathlon** [comment]
Currently to enable debug you need to build by yourself: https://github.com/GoldenCheetah/GoldenCheetah/blob/a065d480cd276cdc9714fc9f2d1310976956c32e/src/Cloud/SportTracks.cpp#L34

**Comment by eaylcr** [comment]
Bug occurs when synchronize or download hits certain activities (possibly those edited as per initial contributor). 
Enhancement to behavior would be report activities that cannot be handled & continue with remaining. Current behavior is to hang.

**Comment by eaylcr** [comment]
Having a play with this bug again: a reasonable proportion (can't confirm 100%) of the activities it hangs on appear to have a date issue when manually exported from ST Web.
Within ST3 &  ST Web the activities are showing correct time - validated because I know what time I leave for work :) 
When exporting both the GPX and TCX however, the time is offset negative 1h. Both GPX and TCX files appear valid in all other respects (both through eyeball and import into GC).
Confirmed that for other activities, exporting produces files with expected times, suggesting that the root cause may lie with ST export api? (although enhancement to graceful handling within GC would be appreciated).

**Comment by amtriathlon** [comment]
Current master allows to enable SportTracks sync code debug at runtime in an attempt to diagnose this issue.

For testing you need to install current master build as explained in: https://groups.google.com/g/golden-cheetah-developers/c/5fZUO9DbJDY/m/dvgmL094BgAJ and then run

`GoldenCheetah --debug-rules "gc.sporttracks.debug=true`

from the command line and provoke the failure, debugging output will be generated in goldencheetah.log file, parallel to your athlete directory.
