### ISSUE TITLE
Bogus spikes in Vo2max trend line

### ISSUE THREAD

**Issue by loc4me** [GoldenCheetah/GoldenCheetah#3180]
On MacOS using v3.5 dev build 1903 I get bogus data in the trend line for vo2max. 

If I used v3.4 with the exact same set of fit files it does not exhibit this behavior. 
![Vo2max](https://user-images.githubusercontent.com/7883335/66678495-e6fd9d80-ec20-11e9-811d-fd3c362fecf5.png)

**Comment by amtriathlon** [comment]
I couldn’t reproduce this issue since I used absolute values, changing to relative (per kg) shows some spikes not present in absolute values, but I have no idea about the cause.

**Comment by loc4me** [comment]
What is used to draw the trend line? Is it just supposed to bet a best fit of the data points or do other parameters / data go into the blue line? The Vo2max data points (blue dots) don't exhibit the jump.

**Comment by amtriathlon** [comment]
In curve settings for the VO2max Estimate there is a couple of radio buttons to select Absolute or per kilogram

**Comment by loc4me** [comment]
I don't see that. I have picked "trends" at the top. Then "library" under that and I picked Vo2max Estimation from the charts panel on the far left. When I used the "More..." menu and pick Chart Settings every thing under curves is greyed out and I can't change anything. I don't see any radio buttons either. 
![image](https://user-images.githubusercontent.com/7883335/67136240-6b7b8d80-f1d8-11e9-978f-b019f7f2a4ab.png)

**Comment by amtriathlon** [comment]
That’s expected, to change a library chart you need to use Edit Chart on the left sidebar, see the wiki

**Comment by loc4me** [comment]
Awesome! I did not know that was there. Changing the method to anything other than the "Extended CP" fixed the large discontinuities up to ~4000 and the estimate now tracks the data points.
![image](https://user-images.githubusercontent.com/7883335/67137290-66720a80-f1e7-11e9-864a-b04c391ba99c.png)

**Comment by MGRSG** [comment]
Hi, I have the same problem on Mac with the 3.5 RC1. In Trends >library, the VO2 Max (Ext) is calculated at the same 3980.6 ml/min/kg than @loc4me 's case. 
<img width="1748" alt="Screenshot 2019-10-22 at 14 50 33" src="https://user-images.githubusercontent.com/56863329/67265540-86a01300-f4e0-11e9-9f24-9eabc3fd135c.png">

This seams to be related to a problem with the Extended CP model, as for the same dates, the Trends > Library > CP History will plot CP (Ext) at 300 W, W' (ext) at 21600 Joules, and P max (ext) at 995.5 W.
<img width="1748" alt="Screenshot 2019-10-22 at 15 22 57" src="https://user-images.githubusercontent.com/56863329/67265505-75570680-f4e0-11e9-826c-ba853a259368.png">

In Activities > CP, the problem is the same, but if I change the date range to "this year" instead of "last two months", then the calculation seams to be ok for this graph.
<img width="1676" alt="Screenshot 2019-10-22 at 14 46 39" src="https://user-images.githubusercontent.com/56863329/67265452-5bb5bf00-f4e0-11e9-8e63-094b84a9ae51.png">
<img width="1676" alt="Screenshot 2019-10-22 at 14 47 12" src="https://user-images.githubusercontent.com/56863329/67265460-5fe1dc80-f4e0-11e9-8463-f2618d411709.png">

Finally, in Activities > Summary, the dates where the problem occurs will show Model fields with the same above values, and will also reveal a problem with per kg values, which are not divided by the weight. 
<img width="1393" alt="Screenshot 2019-10-22 at 14 43 29" src="https://user-images.githubusercontent.com/56863329/67265428-48a2ef00-f4e0-11e9-93eb-d19cf79a52cd.png">

**Comment by amtriathlon** [comment]
> Awesome! I did not know that was there. Changing the method to anything other than the "Extended CP" fixed the large discontinuities up to ~4000 and the estimate now tracks the data points.

The Extended model needs activities longer than 1h to be fitted, may be you don't have activities with power data longer than 1h in the period with spikes?

**Comment by MGRSG** [comment]
Hi @amtriathlon ,
Thank you for this information and for your great contribution to this project. I checked on my side and I have in fact 85 days under < 1h since the last > 1h. 
I exercised for 1 h + yesterday and added it to GC. The model is now N/A. Are there any other requirements, like a minimum number of exercises > 1 h in a certain period of time, or a minimum of time in the different power zones for each training session ?
