### ISSUE TITLE
Dependency is not satisfiable: libgstreamer-plugins-base0.10-0

### ISSUE THREAD

**Issue by bluejay76** [GoldenCheetah/GoldenCheetah#3201]
Unable to install newest stable version of Golden Cheetah on Linux Mint 19.2. Error: Dependency is not satisfiable: libgstreamer-plugins-base0.10-0. I've installed this dependency manually and still get the same error. Have tried installing both amd64 and i386 versions of GoldenCheetah.

**Comment by amtriathlon** [comment]
GC v3.4 needs libgstreamer-plugins-base0.10-0, not version 1.0 which you are likely installing since the former is not available anymore for newer Linux versions. Solutions are to install  libgstreamer-plugins-base0.10-0 from a previous Linux version or to use GC v3.5 RC1 from https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5-RC1
