### ISSUE TITLE
Half of load time is spend doing string control character escape

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3234]
When opening golden cheetah I was waiting 12.5 seconds for my athlete data to load. Profiled and found 73% of that time was spent in RideDBlex. On each string it does 8 independent string replaces, one for each escape.

Ive built a substitution class that uses regex and hash to construct substitution string in 2 passes. With change the athlete data load time drops to 6.5 seconds.

**Comment by amtriathlon** [comment]
I am reopening this issue since their fix seems to be caused this problem:
![Screenshot from 2019-12-07 17-10-27](https://user-images.githubusercontent.com/1444784/70380226-715b3880-1916-11ea-8558-d3736211617b.png)
note that all intervals have the same values for most of the metrics, notably Duration.
The testing file is https://github.com/GoldenCheetah/GoldenCheetah/blob/master/test/rides/2009_07_04_06_09_48.wko, but the problem is general and, for what I have seen up to this point, caused by the write cache part of the fix since:
a) deleting the cache I can see the problem in the cache file after the first save, without the need to restart GC so the load part is not yet involved.
b) reverting https://github.com/GoldenCheetah/GoldenCheetah/commit/fa9a59d60ced1cd0baf0f1650ed3b026f3e5d13d and running after deleting the cache file seems to fix the problem.

**Comment by amtriathlon** [comment]
I changed my mind and opened a new issue since I think it is more clear: https://github.com/GoldenCheetah/GoldenCheetah/issues/3244
