### ISSUE TITLE
Allow any sport from tcx files

### ISSUE THREAD

**Issue by PhilGrunewald** [GoldenCheetah/GoldenCheetah#3291]
At the moment any sport other than "Biking", "Running" leaves the Sport field undefined (or randomly assuming "Swimming"). There are a lot more fun sports out there. Can you allow them in with this simple patch?

FileIO/TcxParser.cpp
line 74
```
        // Sport ("Biking", "Running", "Other")
        swim = NotSwim;
        QString sport = qAttributes.value("Sport");
        if (sport == "Biking") rideFile->setTag("Sport", "Bike");
        else if (sport == "Running") rideFile->setTag("Sport", "Run");
        else if (sport == "Other") swim = MayBeSwim;
```
before the `if` insert: 
```
rideFile->setTag("Sport", sport);
```
That would be great (sadly I cannot build myself, due to the webkitwidgets issue #1086)

**Comment by amtriathlon** [comment]
According to [TCX specification](https://www8.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd) "Biking", "Running" and "Other" are the only valid values for the Sport tag, since we wanted to give special treatment to lap swim files we added an ad-hoc logic to try to guess if it is an "Other" case is a lap swim:
https://github.com/GoldenCheetah/GoldenCheetah/blob/435e8e9bd505fc703cfb1eb7a553cdb16d8ff494/src/FileIO/TcxParser.cpp#L199
Do you want Sport="Other" when this logic fails or you have TCX files with additional values for the Sport field?

**Comment by PhilGrunewald** [comment]
Thanks for the fast response! Wow, that is pretty limited by Garmin. I took the liberty to use the Sport field for all manner of sports from my Polar Flow exports. They save the sport in the file name like so: 
2019-12-20T06-25-29.568Z_Cross-country_skiing.tcx
2019-01-26T05-59-55.502Z_Rowing.tcx
and I just extract it from there. I think GoldenCheetah is absolutely fantastic for these sports and I love to have all data in one place. But I don't want to be accused of messing with the mighty Garmin standards :)

**Comment by amtriathlon** [comment]
In that case it seems harmless to add an else clause to the if in your OP like:
`else rideFile->setTag("Sport", sport);`
I can do this, but it will be after v3.5 release.

**Comment by PhilGrunewald** [comment]
That's very kind of you. I will look into fixing my build environment and try to contribute myself in future. It is a great project. (when installing qt@4 for webkitwidgets my python environment went back from 3 to 2 and I got cold feet)
