### ISSUE TITLE
GC 3.5 crash on fit-file import with automatic "Estimate Distance" processing

### ISSUE THREAD

**Issue by Zepp333333** [GoldenCheetah/GoldenCheetah#3311]
GC 3.5 Release is crashing if automatic Estimate Distance Values it toggled on specific fit-files that:
- produced by Garmin 820 as result of home trainer workout
- contain no speed values
- contain no distance values
- no GPS values
Example fit-file (+ logs) attached -> GC consistently crashes on import of this file. 
[GC_Crash.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4111703/GC_Crash.zip)

Repro steps:
1. Configure GC 3.5 to "Estimate Distance Values" on import (Preferences -> Data Fields -> Prcessing -> Estimate Distance Values -> Import)
2. Import fit-file (attached example) -> crash

**Comment by amtriathlon** [comment]
This is a bug introduced in https://github.com/GoldenCheetah/GoldenCheetah/commit/c299a7237e847ecb968bb034e600d81fc27335e5#diff-9e29aa55c9c7a41e184136d3e316ad27 and it happens with any file, basically it doesn't allow to use Estimate Distance as an automatic data processor since it is unconditionally referencing the config dialog instead to look at stored settings:

https://github.com/GoldenCheetah/GoldenCheetah/blob/8a94666e91140d3b60537609c129ddb81c057a3d/src/FileIO/FixDeriveDistance.cpp#L120
