### ISSUE TITLE
TRIMP(100)_Points Incorrectly calculated for a non run/bike/swim activity with cadence present.

### ISSUE THREAD

**Issue by phuler** [GoldenCheetah/GoldenCheetah#3330]
I started recorded squash sessions using a garmin fenix 6 which I am importing to goldenCheetah automatically via garminConnect -> Strava -> goldenCheetah. 

These were recorded using a generic cardio profile and include the following data fields visible in golden cheetah; time, cadence, heart rate, altitude and temperature. I have attached an example file exported from golden cheetah and the original fit file from garmin connect.
[squashActivity.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4143191/squashActivity.zip)
  
As an estimate of training stress for these activities I calculate a user metric;
```
{
    # only calculate for rides containing HR
    relevant { Data contains "H"; }

    init { HrStress <- TRIMP(100)_Points; }

    value { HrStress; }
}
```
I noticed that the value calculated was significantly lower than expected for these activities. Upon deleting the cadence column the value appears to be calculated corectly. In this case the cadence data is meaningless and I will probably see if I can avoid it being generated in future.

**Comment by amtriathlon** [comment]
TRIMP Points are computed using Time Moving when speed or cadence is available, otherwise Duration is used: https://github.com/GoldenCheetah/GoldenCheetah/blob/cf5d0d1f29982bc155781a36126298af76d8d3fc/src/Metrics/TRIMPPoints.cpp#L85
It is the intended behavior, if speed or cadence are meaningless you can remove it or create a custom metric to compute what you want even if it is present.
