### ISSUE TITLE
Activity List error when using filters

### ISSUE THREAD

**Issue by robolaf** [GoldenCheetah/GoldenCheetah#3341]
I discovered a strange behavior and have not found an issue for it yet… 
What I do:
* Start GC -> Activity view
* use Activity List scroll bar to scroll down
* click into list to select (=> only the 2nd click works!?)
* use scroll bar again to scroll down
=> now it becomes almost impossible to select a workout instead clicks seem to be interpreted as clicks into scroll bar
When I remove the filter it works as expected, again.

Let me know how I can help reproduce…

I use GC 3.5 on Windows.

Thanks.

**Comment by liversedge** [comment]
"When I remove the filter it works as expected, again."
Can you explain?

**Comment by robolaf** [comment]
Sorry, I missed to say that I applied a Filter at the beginning... please see attached video: 
[robolaf 2020-02-17 12-36-05.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4213486/robolaf.2020-02-17.12-36-05.zip)

**Comment by liversedge** [comment]
That is weird!
Will take a look.

**Comment by amtriathlon** [comment]
I can reproduce this issue when the activities list is filtered:

1. the first click selects the activity as can be seen in main window, but it doesn't get the focus. Depending on the position of the clicked activity the list scrolls so the clicked activity becomes positioned in some "sweetspot".
2. second click on the **same activity** gives it the focus but, due to the scrolling mentioned above, repeating the click in the same place behaves as a first click provoking a new scrolling.
3. using up/down arrow keys basically doesn't work since even when an activity has the focus it is lost after the first scrolling.

This is from user's point of view, once you get used to 1. the list is barely usable with the mouse, selection works but you don't get visual feedback, which is confusing, specially when the visible chart doesn't univocally identify the selected activity.

I have not checked what is happening at events level, yet.

**Comment by amtriathlon** [comment]
The problem doesn't seem to be in RideNavigator, if I comment out this line:
https://github.com/GoldenCheetah/GoldenCheetah/blob/7540b69eea4abe8b43017b3205f24a4ebee1f1af/src/Gui/RideNavigator.cpp#L1000
the activity list keeps the focus after selection, even when it is filtered.
Regrettably I have no idea where the focus is stolen and why it happens only when the list is filtered...

**Comment by liversedge** [comment]
I wonder if it depends on the chart being displayed, I know there were issues with opengl based widgets in earlier releases of qt that may have reappeared (e.g. overview stealing focus).

**Comment by amtriathlon** [comment]
No, it happens independently of which charts are visible, both in Tabbed and Tiled mode.

It also happens when Activity View has no charts: normal behaviour when there is no active filter, lost focus when there is any filter active.

**Comment by amtriathlon** [comment]
I found the cause, focus is stolen by:
https://github.com/GoldenCheetah/GoldenCheetah/blob/32a6089f50a3ea365550a1831828f0dfa90bcc80/src/Core/DataFilter.cpp#L2921
which is connected to rideSelected signal.

Now I need to understand what that means and how to fix it without breaking other things.

**Comment by amtriathlon** [comment]
Ok, I think I understand what the problem is, but not how to solve it, yet.

It is complicated, the sequence looks like this:
1) you have a filtered ride list
2) click an entry, rideSelected is emited
3) DataFilter sees the currently selected item has changed, so it recomputes the filter and emit new results in
https://github.com/GoldenCheetah/GoldenCheetah/blob/7540b69eea4abe8b43017b3205f24a4ebee1f1af/src/Core/DataFilter.cpp#L2921
4) this new result list goes all the way around and returns to RideNavigator

**Comment by liversedge** [comment]
Get rid of dynamic searches, no-one uses them.
