### ISSUE TITLE
Export web page chart URL not saved correctly

### ISSUE THREAD

**Issue by bolieu541** [GoldenCheetah/GoldenCheetah#3389]
When exporting a web page chart or uploading it to the cloudDB, the URL is not saved correctly. Space characters are added at the end of the string.

Ex: "https://www.google.ca  "

Then, when importing the chart, the website is not loaded (blank page). We need to edit manually the chart by removing trailing spaces.

**Comment by amtriathlon** [comment]
I can't reproduce this, in fact there are several Web Page charts uploaded to CloudDB which can be downloaded without issues s.t. ErgDB, Training Peaks, Garmin Connect.
Also tried Export/Import without issues, provided the URL doesn't have spaces at the end to begin with since they are not trimmed.
But they are not added either.

**Comment by liversedge** [comment]
it is entirely possible I fixed this as part of another update?
4fd07e7688a210f89666499c6a98ec4db6eb2334

**Comment by amtriathlon** [comment]
It sounds reasonable, but I could not reproduce the issue even with v3.5 release build, downloading pre-existing web charts from CloudDB or export+import works for me, provided I don’t add explicitly trailing spaces.

**Comment by bolieu541** [comment]
I tried the fix from the commit mentionned. It resolves the issue when importing the chart.

FYI, when exporting a chart, it adds a trailing space and the end of json string parameters.
Ex. Title, userData, subtitle and url.
