### ISSUE TITLE
Exported CSV does not include a ride's first record

### ISSUE THREAD

**Issue by jlaue** [GoldenCheetah/GoldenCheetah#3396]
An exported CSV file does not include the first record of a ride, e.g. time equals 0 row in the Edit tab. For a ride captured at 1 second intervals, the exported CSV starts at time at 1 second. Other exported formats (TCX, JSON, KML, etc) do include this initial record of time at 0.

**Comment by amtriathlon** [comment]
This behavior is explicit in code: https://github.com/GoldenCheetah/GoldenCheetah/blob/e5b756b0605823dc0e2faf15790a48aa1ecfc7ca/src/FileIO/CsvRideFile.cpp#L1520

In the powertap case the rationale is likely compatibility with original files, but I'm not sure about the GC case.

**Comment by liversedge** [comment]
Oh my, that is plain wrong isn't it?

In GC the first sample always starts at 0, and on import the samples are offset to always start there.
I think you are right about wko/poweragent compatibility for other formats.

Feels like this is a bug -- the gc format is used by indoor training.

I suspect its not noticed much since the first second is normally when folks are clicking in or leaning over to their computer.

**Comment by amtriathlon** [comment]
Since they are separate cases it is easy to fix GC export format without changing PowerTap one, I can fix this if you are Ok.

**Comment by liversedge** [comment]
Oh, yes please.

I think that is likely the best way - the old poweragent csv files are probably not used much these days (if at all).
