### ISSUE TITLE
Font size issues on Summary tab

### ISSUE THREAD

**Issue by dramaticbulgarian** [GoldenCheetah/GoldenCheetah#3400]
![Screenshot_5](https://user-images.githubusercontent.com/27427058/79195276-420d8880-7e2e-11ea-9551-b7695482e0d9.png)

It appears I'm having a silimar issue to #1420 although in reverse - everything looks and folows the font scaling slider except the summary charts where the font is way too big and appears to cannot be change. Is this a bug or is there any way around this?

Monitor is 3440x1440, GC version is 3.5.

**Comment by liversedge** [comment]
Its because the summary view is actually a web page and scaling the fonts to match has proven to be very difficult. 

Our strategy is to retire the summary view and switch development to the Overview and make sure it covers the use cases needed. So as a result summary view is not getting any attention going forward.

**Comment by liversedge** [comment]
FWIW,Hi-DPI is very well supported now, outside of the summary view.
The bug you referenced was handled with a large number of changes summarised here: #2386

**Comment by dramaticbulgarian** [comment]
Alright, makes sense, thank you so much for letting me know.

**Comment by amtriathlon** [comment]
Summary was deprecated in https://github.com/GoldenCheetah/GoldenCheetah/commit/9d6e08547f14e79c8aef1f9688336c76c2497775
