### ISSUE TITLE
Cannot Enable Python > 3.6

### ISSUE THREAD

**Issue by srwareham** [GoldenCheetah/GoldenCheetah#3433]
Thanks for the fantastic software!

When attempting to enable python in GC, I get the following error message:
![image](https://user-images.githubusercontent.com/3392952/81202012-fe70ef00-8f93-11ea-92ba-acaa0e99d58c.png)

I'm running GC on Arch Linux, which generally uses the most recent package version possible. Is it intended behavior that GC be pinned specifically to a single python version, in this case 3.6? Looking at the latest development build, it seems 3.7 will be supported, but not 3.8. Forgive my ignorance with embedded python, but can multiple versions be allowed?

Without python enabled, this is the GC version info (using AppImage):
![image](https://user-images.githubusercontent.com/3392952/81203376-e4381080-8f95-11ea-9a25-0f6ee3b6366a.png)
I tried setting the Python Home configuration to each of the below, but received the same error every time:
 *  /usr/bin/python
 *  /usr/bin 
 * leaving it blank

**Comment by amtriathlon** [comment]
Due to the way Python is embedded you need to install the same version used at build time, currently they are Python 3.6 for GC 3.5 and Python 3.7 for GC 3.6dev, we may change this in the future, but this is the current situation.
In general it is not such a good idea to mess with system Python for applications use, I would suggest to install a separate version for GC embedding, for example: https://groups.google.com/d/msg/golden-cheetah-users/_LAtBU4ETbM/NHC1eMIXDQAJ
