### ISSUE TITLE
Activity start time for imported iBike CSV files is incorrect

### ISSUE THREAD

**Issue by BillOsler** [GoldenCheetah/GoldenCheetah#3439]
In version 3.5 Build 3991 the start time for activities imported from Velocomp/iBike CSV files is incorrect.  The activity start time shown in Golden Cheetah Details is the UCT start time rather than the local time.
The iBike CSV files have time stamps for each record in UCT time but it appears that when the json files are built the time stamps are interpreted as local time rather than UCT.
The CSV files do specify the correct local start time in the second line of the file as 6 comma separated values which are, in order:
year, month, day, hour, minutes, seconds
[CSV export copies.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4609708/CSV.export.copies.zip)

**Comment by amtriathlon** [comment]
This behavior was introduced by https://github.com/GoldenCheetah/GoldenCheetah/pull/3105

**Comment by paulj49457** [comment]
Hi Ale,
  I'm happy to look at this issue if it still needs fixing, or is there a work around given that its in the Parking Lot ?
Regards,
Paul.

**Comment by amtriathlon** [comment]
The workaround is to select the date manually at ride import, but the main reason it is in the Parking Lot is nobody seems to be interested in to fix it.
 I can assign it to you, if you like but please, don't reformat the code nor include the fix with other changes if you want your PR merged.

**Comment by paulj49457** [comment]
Hi Ale,
   Thanks for the info, in that case I'll take a look at the change.

   Also regarding your comment about not fixing it with other changes, I wasn't intending to that! I understand where possible it is better to have small, coherent, decoupled pull requests, so allowing independent reversion (should it be required).  The only reason I added the re-implemented overwrite functionality #621 & #3696 the file exclusion capability to the auto import filtering pull request #3770, was that they are so intertwined changes that to separate them would cause a merge order dependency chain, and possibly result in a very difficult merge.
Regards,
Paul.

**Comment by paulj49457** [comment]
ok, so I understand the problem, but before I fix it there is a slight confusion in the provided iBike file (see end of message):

The ride appears to start at 13,34,34, and UTC is 17:34:35Z, but the offset is -5 hours, so is the 13,34,34 using summer time given its after the end of March when summertime usually starts?

So I can easily fix it so that GC uses line 2 (13,34,34), or I could read in the UTC offset and work back from the UTC time of the first point, but in this example that would not be correct?

So which of the above would you like coded?

Regards
Paul

iBike,13,english
2020,4,28,**13,34,34**
,<-Weight (lb) Energy (kJ),Aero,Fric,dt,Ref Elev (ft),Climbing (ft),Wheel Circ (mm),Ref Temper (degF),Ref Press (mbar),Internal,Wind Scaling,Riding Tilt (%),Cal Weight (lb),Internal,Cm,CdA (m^2),Crr,Note,**UTC Time Zone** Offset,Creator,Ride Duration,Ride Distance (mi),Calories Burned (kcal),Trainer Ride,Device
179.000000,465.024826,0.210766,8.920705,1.000000,0.000000,512.800000,2096.0,58.73,1013.25,-8,0.86288,-0.70,179.0,0.000,1.0204,0.24426,0.004200,,**-5.00**,"iBike Newton, 7.12",1:19:35,20.87,444.6,FALSE,iBike Newton
Speed (mph),Wind Speed (mph),Power (W),Distance (miles),Cadence (RPM),Heartrate (BPM),Elevation (feet),Hill slope (%),Temperature (degF),Lap Marker,Annotation,DFPM Power,Latitude,Longitude,Timestamp,Moving Time,CdA (m^2),Air Dens (kg/m^3)
16.6,16.1614,111.3496,0.0046,60,64,541,1.1768,75,1,,153,0,0,2020-04-28T**17:34:35Z**,0,0.2443,1.1653

**Comment by amtriathlon** [comment]
That seems a clean solution to me, thank you!
