### ISSUE TITLE
TTS file import

### ISSUE THREAD

**Issue by TriScott** [GoldenCheetah/GoldenCheetah#347]
Has any work been done to allow direct import of the workout files from Tacx Trainer Software?  I know you can export from TTS as Polar .hrm files which can be imported, but being able to natively load the .tts format would be more convenient.

Part of the reason I ask is because I actually put a decent amount of work into cracking the .tts format myself previously.  I'd say I am 90% of the way there (stopped when I had the ability to extract the power data which was all I really cared about).  If the feature appeals to anyone I could probably help.

**Comment by drockmd** [comment]
Any updates on this? I do not see the ability to import TTS files into Golden Cheetah in the current release. 

I recent switch to Wahoo, because of Tacx's terrible customer service, but have a ton of historical ride data and purchased courses still on the tacx platform that I would like to import into a program compatible with the kickr. 

Any info would be super helpful.

Thanks, 
Derek

**Comment by mk4th** [comment]
Hi @TriScott ,
Do you still have your TTS decode somewhere?
I want to implement the convertor.
Thanks

**Comment by ericchristoffersen** [comment]
Hi. I just started working on this. Can we please reopen? Some of my tts files have location data, some others don't. Would need it to be tested by a broader audience. Maybe have something to play with in 1 or 2 days.

**Comment by liversedge** [comment]
send a note to the forums to request some, you may get a fair few.

**Comment by ericchristoffersen** [comment]
I think this finished and ready to go. Would love to hear feedback from folks that can compare with the silo'd tacx experience.
