### ISSUE TITLE
sportplus+ bluetooth not detected

### ISSUE THREAD

**Issue by drguell** [GoldenCheetah/GoldenCheetah#3471]
Hi,

I have a sportplus+ device and I recive the message:

`"Ignoring the CSC service for device..."`

And when I look at code, this is because goldencheetah doesn't found any power, cadence, etc device.
I wanted to know if is possible to include it and that the program recognise it.

Thanks.

**Comment by amtriathlon** [comment]
The "Ignoring the CSC service for device..." was intended to notify when power sensor is present the CSC service is ignored since it is redundant and cause problems, but it is misleading in this case.
If you are not seeing any ""Discovering details for service" from:
https://github.com/GoldenCheetah/GoldenCheetah/blob/15b491409a4083baa9eb781fb02cbd53d0fff48c/src/Train/BT40Device.cpp#L150
it means no services are reported by this device, so GoldenCheetan has nothing to monitor.

**Comment by drguell** [comment]
Thanks, I'm trying yo discover this information. 
I'll try to get it this week.

PS: I edit OP again.

**Comment by ericchristoffersen** [comment]
I ran into something similar with kurt kinetic inride. Where do i pit the support? Can i simply add it to bt40?
