### ISSUE TITLE
Muscle mass, lean mass and bone mass doesn't sync using Withings cloud connection

### ISSUE THREAD

**Issue by Pyrrhos512** [GoldenCheetah/GoldenCheetah#3497]
Hello,
I have an issue with the withings cloud, Golden Cheetah is not able to download the muscle mass, the lean mass and the bone mass from Withings but it got the body fat mass and percent.
I already checked (each time I delete the weight data in Golden Cheetah) : 
- All weight data is show in Health Mate (the Withings app).
- If I download by myself the data from withings, I have all weigths (.csv file).
- If I reorder the data given by withings to import it from the .csv to Golden Cheetah it works.
- I disconnected and reconnected Withings from Golden Cheetah and it doesn't change anythings.

I didn't tried to reinstall Golden Cheetah.

Sorry if the issue was already reported (did'nt see it).
Thank you for your work.

Pyrrhos512

**Comment by amtriathlon** [comment]
Fat Free Mass should be imported as Lean Mass according to the code:
https://github.com/GoldenCheetah/GoldenCheetah/blob/6ca1bd9a9c213abaed728f59864e6a4d4689e087/src/Cloud/WithingsDownload.cpp#L248
Muscle Mass and Bone Mass are newer additions to the API not handled by GC downloading code: https://developer.withings.com/oauth2/#tag/measure%2Fpaths%2Fhttps%3A~1~1wbsapi.withings.net~1measure%3Faction%3Dgetmeas%2Fget

**Comment by funkymaster** [comment]
I'm not able to implement it by myself right now, but I think I found a solution for Muscle Mass and Bone Mass because these Body values are already implementd in GC.

According to this: https://developer.withings.com/api-reference#operation/measure-getmeas
Case values should be added here
https://github.com/GoldenCheetah/GoldenCheetah/blob/6ca1bd9a9c213abaed728f59864e6a4d4689e087/src/Cloud/WithingsDownload.cpp#L248
```
case 76 : thisReading.musclekg = value; break;
case 88 : thisReading.boneskg = value; break;

```
BodyMeasure values should be added here
https://github.com/GoldenCheetah/GoldenCheetah/blob/6ca1bd9a9c213abaed728f59864e6a4d4689e087/src/Cloud/WithingsDownload.cpp#L196
```
w.musclekg = r.musclekg;
w.boneskg = r.boneskg;

```
Maybe someone can add those lines.
Thx!

**Comment by funkymaster** [comment]
@amtriathlon
I'm not sure if you have seen my last comment.
Could you please add those lines?

Thank you.

**Comment by amtriathlon** [comment]
> @amtriathlon I'm not sure if you have seen my last comment

Yes, I saw it.

> Could you please add those lines?

No.

**Comment by funkymaster** [comment]
Ok, thank you for your reply.
What's wrong with my suggestion?

**Comment by amtriathlon** [comment]
> What's wrong with my suggestion?

That code was included more than a year ago in the commit closing this issue, see above.

**Comment by funkymaster** [comment]
Oh, I am very sorry! I have overlooked this.
