### ISSUE TITLE
After changing Language, trends:Charts are still using old language.

### ISSUE THREAD

**Issue by OklariU** [GoldenCheetah/GoldenCheetah#3509]
Hello

I decided to change Settings:Language French to English, Apply, Restart GoldenCheetah app.
Some language strings still in the  French language.

trends:Charts

OS: W10 LTSC 1809 17763.1282 (French)
GoldenCheetah: latest GoldenCheetah_v3.6-DEV2006_x64.exe

**Comment by amtriathlon** [comment]
This is by design: all texts the user can customize are translated when the object is created, if you change the language afterwards they will remain unchanged to preserve user customizations.

Depending on what level of customization you want to preserve there are several alternatives:

- Full reset: create a new athlete and re-import your activities to have all texts in the new language 
- Charts reset: Use View > Reset View and Reset to Default in Charts on Trends sidebar to recreate them. To preserve customized charts: export them before reset and reimport afterwards.
- Manual edit: Metadata and Zone names.
