### ISSUE TITLE
[Feature request] Fat mass and Fat percent

### ISSUE THREAD

**Issue by jgpallero** [GoldenCheetah/GoldenCheetah#3533]
In Tools->Options->Athlete->Measurements the fields "Fat mass" and "Fat percent" are independent each other, i.e., I can introduce values as Weight=70, Fat percent=10 and Fat mass=9, being incongruent the Fat mass with the Fat percent. It would be nice if these two fields were coordinates and entering data in one updates the other

**Comment by amtriathlon** [comment]
Lets make this a consideration for https://github.com/GoldenCheetah/GoldenCheetah/issues/2872

**Comment by jgpallero** [comment]
I can see that this request was closed and also closed the #2872, to which this is related according to the Ale's comment. But I've downloaded the last build (February 1st, Build id: 4003), and the "Fat mass" and "Fat percent" are still independent. Is this request still under consideration?

**Comment by amtriathlon** [comment]
They are redundant, in current v3.6 you can decide which one to maintain and remove the other in Measures configuration. Then you can to display or chart the removed one using a formula.

We can do that in default config if there is some agreement about which one to keep as primary measure.

**Comment by amtriathlon** [comment]
To store both fields is redundant, the are included so the user can select which one to maintain and since Withings and Today's Plan downloaders have prevision for boths, if you update manually you can fill the one you prefer and let the other in zero.

I added a couple of changes so Athlete BodyFat and Athlete BodyFat Percent metrics use whatever of the 2 fields is available, other situations can be handled by the user with simple formulas, but to update one from the other in the table is not possible.
