### ISSUE TITLE
OpenGL not working on macOS 

### ISSUE THREAD

**Issue by helmling** [GoldenCheetah/GoldenCheetah#3594]
(commit 8b651b50d breaks Activity overview and User dashboard)
attached patch fixes problem by disabling openGL on mac and windows

**Comment by helmling** [comment]
[patch.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/5183746/patch.txt)

**Comment by liversedge** [comment]
how is the issue manifested ?
why mention MacOS but code affects Windows too ?

**Comment by helmling** [comment]
- Overview for activity and trends is showing only very briefly and only the first time, than this window remains plain
- Users  Dashbloard is not showing at all (blank window)
- Fix was choosen to be consisten with the setting in "RCanvas::RCanvas"

**Comment by liversedge** [comment]
Thanks. It looks like the issues are a little more nuanced; OpenGL rendering on windows falls back thru GPU, Angle and Software renderer- the reports of issues there are related to bad implementations by AMD.

On MacOS OpenGL should be supported but is being deprecated by Apple as they encourage users to move to Metal- but this is not going to be supported till Qt6.

For now I will apply your change, but this means Nvidia owners on Windows are being short changed because AMD write crappy OpenGL drivers.
