### ISSUE TITLE
Wrong load value - Video chart

### ISSUE THREAD

**Issue by ghost** [GoldenCheetah/GoldenCheetah#3608]
On image you can see Target power with negative value. But in Video chart it is displayed as positive. During whole ride i noticed that it is wrong only when Target power is -0.X%. But it shows correct negative load value (in Video chart) when Target power is -1.X%
http://89.212.19.139/wrong_load_value.png

I'm using latest Dev build, from Sep 15 2020, in Windows 10 (virtualbox)

**Comment by ericchristoffersen** [comment]
Can you please share the workout file?

**Comment by amtriathlon** [comment]
The problem is independent of the workout file Eric, when slope is -0.xxx the integer part is zero and the sign is lost:
https://github.com/GoldenCheetah/GoldenCheetah/blob/73e175e0f31fcf29a3985ef2967d47285b4f8da7/src/Train/VideoWindow.cpp#L419
I have not checked if Elevation widget has the same problem.

**Comment by kub3r4** [comment]
@ericchristoffersen 
It was demo Monte Baldo. You can get it here https://www.cycle-in-motion.de/?page_id=1192
