### ISSUE TITLE
Bug in setPowerScaleFactor in Fortius.cpp

### ISSUE THREAD

**Issue by marcoveeneman** [GoldenCheetah/GoldenCheetah#3616]
I believe i found a bug in the following piece of code of the Fortius driver:

https://github.com/GoldenCheetah/GoldenCheetah/blob/e363f57a744e103a86ae3c9ce7eec6a849b7173a/src/Train/Fortius.cpp#L104

```cpp
void Fortius::setPowerScaleFactor(double powerScaleFactor)
{
    if (weight < 0.8) weight = 0.8;
    if (weight > 1.2) weight = 1.2;
    
    pvars.lock();
    this->powerScaleFactor = powerScaleFactor;
    pvars.unlock();
}
```

Looks like this function is overwriting the `weight` member variable instead of limiting the range of `powerScaleFactor`, probably a copy-paste error 7 years ago.

**Comment by amtriathlon** [comment]
@michelrdagenais is working on the Fortius driver and he has requested feedback on users forum, perhaps you can contribute your experience so he can review this change.
This is the thread: https://groups.google.com/forum/#!topic/golden-cheetah-users/KyzS3QBip7A

**Comment by michelrdagenais** [comment]
Indeed, this is a bug. It looks like it was inserted in 2013. I am not sure where it would have been copied from. The equivalent function in Imagic does not have the bug, even though it was inspired from the Fortius driver much later. This is not called in my setup, probably because I have not set any calibration factor.
> Looks like this function is overwriting the `weight` member variable instead of limiting the range of `powerScaleFactor`, probably a copy-paste error 7 years ago.
