### ISSUE TITLE
Workout name as Details > Route

### ISSUE THREAD

**Issue by ghost** [GoldenCheetah/GoldenCheetah#3630]
It would be nice to have Workout name automatically saved as Route in Details tab in activities.

Example:
My workout file names (for gpx and TTS) are route names. 
And I also use Route (in Details tab) as my Strava Activity name. So when you save your workout it could add filename / workout name as Route in Details tab.

I think Route is most logical for gpx and TTS files.

**Comment by amtriathlon** [comment]
This maybe reasonable for simulation rides, but for other workout types other alternatives may be desirable. Anyway, currently no metadata, except for time and date, is passed from Train sessions to imported activities and this would require to implement a mechanism for that, so I will put this in the parking lot waiting for a developer interested in the feature.

**Comment by adutton** [comment]
I'd like to second this feature request.  Currently if I train a simulation ride, there are no notes, no workout title, and no route name.  It makes it really hard to tell what workout I was attempting to do and makes updating the activity a manual step.

**Comment by amtriathlon** [comment]
I would suggest to complete metadata when the activity is imported and all the information is fresh in your mind, I don't think this would be implemented anytime soon since it requires to re-design the way train workouts are imported for little benefit.

**Comment by ZajtiM** [comment]
I just made last tests for this feature in my build. It works for both, "Activity->Import from file" and for Train view workouts.

Since i have "Route" column in Activities list in Activities view, this feature can be very useful. For both multiple files import and when saving Train workouts. I often do two workouts consecutively, so why do extra work by editing activities if it can be automated.

So if you're importing multiple files and file names are route names, it can be useful to use this feature to populate "Route" field on import (for all files/imports). And if you have Workout files in Train view, that are named by routes, it can populate "Route" field when workout is saved. Can also be useful for ERG files even tho they don't have "route". But adding extra info for better transparency is the way to go.

Here is extra QComboBox in which you need to select one of the options to populate "Route" field. If you don't select any option "Route" field will not be populated. Two options are because Route names are not obtained the same way.
![Import_add_Route](https://user-images.githubusercontent.com/74620728/99583713-3c8ba880-29e4-11eb-9827-269d4816b0af.png)

QComboBox is not visible when not needed, just like "Select Date...".

**Comment by amtriathlon** [comment]
I have 2 comments:
1) To use the file name to populate metadata is an unrelated issue and source filename is an already imported field, look at Extra tab.
2) To ask the user if (s)he is importing a workout when the program already "knows" this seems a bad practice, IMHO.

To use the context to retrieve additional data when importing workouts may be acceptable to avoid passing over the CSV file (with the caveat metadata will be lost on abnormal termination), but for this RideImportWizzard should differentiate when it is called from TrainSidebar to do that automatically.
