### ISSUE TITLE
Elite Turbo Muin 2013/2015 trainers should be rpm based, not speed based

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3644]
Elite Turbo Muin trainers are direct drive, they have no wheel to size. They are currently defined as speed based trainers but should be changed to rpm based trainers.

David from gc user thread is going to measure speed/power using a power meter, at that point we can update trainer definition so it is rpm based.
 
Thread is here:

https://groups.google.com/g/golden-cheetah-users/c/U7H4DHVbjpU

**Comment by amtriathlon** [comment]
I don't think this change is worth the special case, even when it is technically correct, the value to set as wheel circunference is well documented, currently we need it for speed and the user likely needs to know it to pair the trainer with a watch.
https://elitesrl.zendesk.com/hc/en-us/articles/115005042389-Set-wheel-circumference-on-an-external-device-with-Turbo-Muin-Smart-B-

**Comment by ericchristoffersen** [comment]
I had a guy with one of these trainers who was helping but he went radio silent. Its a one line change that would mean that wheel circumference would be ignored and power would be correct. Speed from trainer is ignored in slope mode, and with a pending change will soon also be ignorable in ergmode. I really hope I can get feedback from the elite user, that will let me also finalize trainer inertia.

That is awesome you found the source of the magic 13.2.

PS: I don't understand what 'pairing with watch' has to do with us.

**Comment by amtriathlon** [comment]
> That is awesome you found the source of the magic 13.2.

Plain old Google search

> PS: I don't understand what 'pairing with watch' has to do with us.

The user who wants to have speed/distance in their watch needs the same information.

In summary, this is moot to me and trainer inertia seems unrelated, go ahead if you want to do this change or lets close this.

**Comment by mjunkmyjunk** [comment]
the elite turbo Muin is a wheels off trainer but it also does not have power transmitted. In fact, I believe there's nothing being transmitted at all and it's basically a wheels off dumb trainer (using fluid as resistance) 

like the web you linked, the user is likely using a Misuro B+ unit which basically converts RPM into Power (not sure about cadence) which is why wheel circumference is needed. 

since this is a dumb trainer so to speak, and there's no way to control the trainer, trainer inertia / trainer erg mode seems to also be moot.

I have a friend with this trainer and the Misuro B+, what exactly are you looking for? I can relay the question.
