### ISSUE TITLE
Cannot add Withings Cloud Account

### ISSUE THREAD

**Issue by afennell** [GoldenCheetah/GoldenCheetah#3666]
Dears
Thank you for your valuable work
Sorry but I'm not able to associate my withings account,
it always returns a blank modal frame with "Invalid clientid".
Credentials are fine, access has been tested with chrome.
I'm also a developer, in the case you need help, please address me to the right spot.

Cheers
Adriana

**Comment by amtriathlon** [comment]
Hi Adriana, are you using your own build or an official (which) one?

**Comment by afennell** [comment]
Hi
OS: Ubuntu Focal (5.4.0-53-generic #59-Ubuntu)
GoldenCheetah: (official focal release)
3.5-DEV1810
Build id: 3970
DB Schema: 149

In other words, I just installed it from the official repositories

**Comment by amtriathlon** [comment]
It is likely that build lacks the secrets required to access online services, besides to be an older development version from 2 years ago, please use one of our official builds from: http://www.goldencheetah.org/

Otherwise, if you want to build by yourself or fix that build, you need to register a new key and set in https://github.com/GoldenCheetah/GoldenCheetah/blob/f30dd0a9c562482b0d6548c0990990453b1a1d93/src/gcconfig.pri.in#L261
