### ISSUE TITLE
Invisible widgets blocking workout control in train view

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#3754]
Since the meter widgets on the video view have some weird behaviour when scrolling, they can block the workout control. This is most obvious with the map widget (since it's the biggest one) but happens with all available widgets.

When there are no GPS data, the workout control is still blocked by an invisible map window.  In that case, it's just not obvious why the controls aren't clickable.
I had to kill the GC process a few times because I wasn't able to click the stop button to end a workout and couldn't figure out why.

![Screenshot from 2021-01-03 14-48-40](https://user-images.githubusercontent.com/781063/103480158-ed9ea480-4dd2-11eb-9f24-4e2a2ecffb2d.png)

**Comment by amtriathlon** [comment]
It is a known issue on Linux, it doesn't happens on Windows, AFAIK.

I will keep this open, but I am afraid it will not be fixed anytime soon since there is no viable solution at sight. Qe decided to enable the widgets on Linux anyway since users may find they useful even with this limitation, the alternative is to disable them and use Live Map chart and Dials which are well behaved.
