### ISSUE TITLE
Daum TRS 8008 "Cannot connect to daum"

### ISSUE THREAD

**Issue by jotrax** [GoldenCheetah/GoldenCheetah#3772]
This issue is a follow up to pull request #3691

Using build 4003 from Jan 5 2021 I just tried to connect to my Daum TRS8008 under Ubuntu 18.04. I used the "Add device wizard", selected Daum Cockpit and it was found by the scan on the correct tty port. Shortly after connecting, it gave me an error msg: "Cannot Connect to Daum"

Reply from @chrta: "_I suspect, that your cockpit reports another id and therefore it does not add the required delay to the commands. If you can somehow activate the qt logger and set it to debug loglevel you should see a log line, like Daum cockpit type: 0x40. If it is 0x40, the delay is missing. If it is 0x64 (as mine) there is something else wrong._"

I will attach the log information in the evening.

**Comment by chrta** [comment]
I cannot test the version, because downloading the AppImage currently always fails. But your cockpit id is currently not handled by the code.

As far as i know jErgotrainer does not check the cockpit id and it waits at leas 50 msec between commands:
```
// wait at least 50 ms before next command could be sent
Thread.sleep( cmdWaittime );
```
This is only done for the 8008 TRS Pro here, because we did not want to introduce issues for devices i could not test.
Without the 50msec delay my 8008 TRS pro also is not working, since the internal firmware seems to be too slow.

@jotrax Are you able to compile this project? If you can, you can test https://github.com/chrta/GoldenCheetah/tree/fix-daum-8008-42 That adds your cockpit id and also sets the same delays as for the 8008 TRS pro (and as jErgotrainer).

**Comment by jotrax** [comment]
I just tried to compile the code (QT 5.15.2), but it fails after a while at:
`/usr/bin/ld: CloudService.o: undefined reference to symbol 'inflateEnd'`
Any idea?

**Comment by amtriathlon** [comment]
> As far as i know jErgotrainer does not check the cockpit id and it waits at least 50 msec between commands:
> 
> ```
> // wait at least 50 ms before next command could be sent
> Thread.sleep( cmdWaittime );
> ```
> 
> This is only done for the 8008 TRS Pro here, because we did not want to introduce issues for devices i could not test.
> Without the 50msec delay my 8008 TRS pro also is not working, since the internal firmware seems to be too slow.

Perhaps we can also do that, it seems to be safe and more general than current approach

> @jotrax Are you able to compile this project? If you can, you can test https://github.com/chrta/GoldenCheetah/tree/fix-daum-8008-42 That adds your cockpit id and also sets the same delays as for the 8008 TRS pro (and as jErgotrainer).

If you create a PR CI builds will be automatically triggered and they can be accessed as explained in https://groups.google.com/g/golden-cheetah-developers/c/5fZUO9DbJDY

**Comment by chrta** [comment]
@jotrax  I would expect that the code from the pr works for you with an empty profile string. If it does not work, you can test to write a 100 into the profile string (or a 200). This would set the delay between the commands to 100msec or 200msec instead of 50msec.

**Comment by jotrax** [comment]
Unfortunately I didn't mange to compile the branch on my local build environment, but the CI obviously finished - thats good!
I'll give it a try this evening and give feedback to you guys!

**Comment by jotrax** [comment]
Gentlemen, I can give good news. With the cockpit version patch it is working now. Thanks

**Comment by mtheli** [comment]
I think jErgoTrainer does it properly. I would strongly recommend to also add the minimum delay of 50ms to all other daum bikes too. Because in the original documentation of the daum protokoll (http://www.daum-electronic.de/de/download/interface_2003_offiz191203.pdf) there is one very important section (sorry german only):

_Wichtig: Wenn der Mindest-Abstand zwischen den Datenpaketen nicht eingehalten wird oder die  Befehle nicht richtig verwendet werden, können Daten oder Code im Cockpit überschrieben werden! Im Update-Modus werden andere Befehle verwendet._

If the delay is missing, or the commands are not used properly, data or code could be overwritten in the cockpit.

**Comment by reiniaustirol** [comment]
hello, what can i do, my daum 8008 trs3 is found but when starting a training it says “no connection to daum”, i connected the trainer serially to usb and selected the correct com.  Unfortunately, I am not a programmer and therefore don't know much about it.  thanks

**Comment by chrta** [comment]
@reiniaustirol Maybe setting the profile strings helps, see the commit message of https://github.com/GoldenCheetah/GoldenCheetah/pull/3775/commits/25d1126ae92ab2bfaf74405354ccd1ca6ee02ef6

So i would suggest you try the string `50_sound ` as a profile string of the Daum bike. This results in the same delay settings as for my 8008 TRS pro. You could also try to increase the 50 to maybe 100, if this does not work.

**Comment by reiniaustirol** [comment]
thank you ... sorry, where do I have to enter this, don't know my way around?  am not a programmer

Von meinem iPad gesendet

**Comment by chrta** [comment]
It is a setting that is visible when you add your Daum Cockpit as a training device. There is a text box where you can enter the string. This text field is labeled with something like "Profile". I think it is somewhere near the setting of the serial port.

**Comment by reiniaustirol** [comment]
it worked ....... many, many thanks
Best regards

Von meinem iPad gesendet

**Comment by amtriathlon** [comment]
I've added an entry to FAQs with this information for future reference, please check and fix to your taste @chrta
