### ISSUE TITLE
Activity recorded by Garmin barametric device doesn't export to Strava with the correct Creator tag

### ISSUE THREAD

**Issue by cobase2010** [GoldenCheetah/GoldenCheetah#3824]
The original issue https://github.com/GoldenCheetah/GoldenCheetah/issues/2535 was closed three years ago.  However, I am still seeing the problem of Strava ignoring elevation information as the exported TCX file doesn't specify a specific Garmin device name and ID. It only contains a generic creator tag like this: 

" <Creator xsi:type="Device_t">

                <Name>Garmin TCX</Name>
                <UnitId>0</UnitId>
                <ProductId>20119</ProductId>
                <Version>
                    <VersionMajor>0</VersionMajor>
                    <VersionMinor>0</VersionMinor>
                    <BuildMajor>0</BuildMajor>
                    <BuildMinor>0</BuildMinor>
                </Version>
            </Creator>
"

If I change "Garmin TCX" to "Forerunner 935" (one of the devices Strava recognize as having barametric support), Strava will take the elevation information recorded by the watch instead.
I tried this on both 3.5 and 3.6 but with the same result.

_Originally posted by @cobase2010 in https://github.com/GoldenCheetah/GoldenCheetah/issues/2535#issuecomment-779475140_

**Comment by paulj49457** [comment]
I'm happy to look at this issue if one of the admins wants to assign it to me.

**Comment by amtriathlon** [comment]
> The original issue #2535 was closed three years ago. However, I am still seeing the problem of Strava ignoring elevation information as the exported TCX file doesn't specify a specific Garmin device name and ID. It only contains a generic creator tag like this

That solution was enough to fix the issue 3 years ago, it looks like Strava rules are more stringent now, so lets consider this a new issue.

**Comment by paulj49457** [comment]
I have fixed this, but my devices are a "Garmin FR910XT" & "Garmin Edge 800", so can you test whether prefixing your Forerunner 935 with "Garmin", so the device name would be "Garmin Forerunner 935" works when you upload it to Strava? 
Otherwise I need to fix it a bit more by removing "Garmin ", I've searched in the Strava site and in the TCX file schema but there isn't any useful information on the format of this field.

**Comment by cobase2010** [comment]
Adding Garmin should have no problem for Strava to understand the device. Would this fix also affect ".fit" export and the direct Golden Cheetah to Strava sync as well?

**Comment by paulj49457** [comment]
Fixed by -->  #3826 TCX export to Strava with the incorrect Creator tag 

The proposed fix only affects the exported TCX file, and it will now export what GC holds as the device type (see examples below), and looking in my TCX files they contained the altitude information exported from GC. Searching the code I cannot find any smoothing applied to the Altitude on import or export, although you can manually "Fix Elevation Errors" using the option in the Edit drop down menu which will modify the values held in GC, and then in any exports.

Looking in the FIT file export the device is coded as integer rather than a string description as its a compact binary file. The mapping between device string names and integer values supports the FR935 (as per below) so the FIT file will contain something representing 2691, whilst the TCX will now contain "Garmin FR935" for your device.

.............
  case 2530: return "Garmin Edge 820";
  case 2531: return "Garmin Edge 820 Explore";
  case 2544: return "Garmin Fenix 5s";
  case 2604: return "Garmin Fenix 5x";
  **case 2691: return "Garmin FR935";**
  case 2697: return "Garmin Fenix 5";
  case 2713: return "Garmin Edge 1030";
.............

**Comment by cobase2010** [comment]
Thanks for the quick fix. Is it possible to also fix the FIT file export to use the device name instead of a code, which Strava doesn't understand?

**Comment by amtriathlon** [comment]
> Fixed by --> #3826 TCX export to Strava with the incorrect Creator tag

I am afraid it is not that simple. Do you or the OP tested that just changing the device name fixes this issue?

If you looked to the antecedents there are 2 aspects to consider:
1) Once the generated file is uploaded to Strava the altitude is the one in the TCX file, that the crux of the problem.
2) The generated TCX file needs to be accepted by Garmin Connect, which is the closer we have to a reference implementation.

**Comment by cobase2010** [comment]
Ok, this is the original fit file exported from Garmin Connect. If I upload this one to Strava, I got an elevation gain of 515ft, which is exactly what I see when I recorded on my watch.
[6283292625_ACTIVITY.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5992684/6283292625_ACTIVITY.zip)

This is their TCX export. When I upload this to Strava, the total elevation gain is now 661ft! My guess is that TCX file doesn't contain the total elevation gain information computed by the device (which uses 3s smoothing), so Strava simply just added up all the elevation differences. I suspect GIT file does contain that information, hence Strava was able to extract that after uploading.
[activity_6283292625.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5992687/activity_6283292625.zip)

This is the GodenCheetah exported TCX file without your device name fix. When uploaded it shows 465ft elevation gain as Strava applies its own elevation correction due to the lack of barometric device name in this file. If I change the device name to "Garmin FR935", it still shows 465ft elevation gain, which means Strava doesn't recognize "Garmin FR935" as a valid barometric device name. However, if I change the device name to be either "Garmin Forerunner 935" or just "Forerunner 935", it now shows 661ft elevation gain, same as the Garmin exported TCX file.
[GoldenCheetahExport_TCX.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5992714/GoldenCheetahExport_TCX.zip)

So ideally if we can somehow encode the correct Garmin Barometric Watch string (or code) in this exported "FIT" file, it should achieve the same elevation gain information shown on the device. Currently, without any fix, it shows 465ft elevation gain on Strava, essentially Strava ignored the elevation information stored in this file due to the lack of recognizable known barometric device identifications.
[GoldenCheetahExport_FIT.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5992737/GoldenCheetahExport_FIT.zip)

Hopefully this makes sense.

**Comment by paulj49457** [comment]
Hi Mark,

   Thank you for the extra information and additional testing, so its easy to modify the fix to change the mapping from "Garmin FR935" to ""Garmin Forerunner 935" or just "Forerunner 935", and as I understand this will fix the problem when its exported in the TCX file.

   BUT first I need to spend a bit of time searching to see what the official device names should be, as I expect this may affect other Garmin devices when exported to Strava, as I see that some of the others (such as "Garmin FR630" & "Garmin FR230") appear in an abbreviated form as well.

Regards,
Paul

**Comment by paulj49457** [comment]
It would appear what I need to ensure the device string names are correct is the Strava "device database" (see below), although we could just fix it on a device by device basis.....

Brief guide to what TCX & FIT data Strava use:
https://developers.strava.com/docs/uploads/

Elevation for Your Activity: which helpfully says "Strava uses a variety of methods to calculate elevation"....
https://support.strava.com/hc/en-us/articles/216919447-Elevation-for-Your-Activity

Elevation on Strava FAQs -- says "If your device has a barometric altimeter and it is included in our **device database**, the activity page will display the elevation that the device recorded into the file."
https://support.strava.com/hc/en-us/articles/115001294564

**Comment by amtriathlon** [comment]
IMHO to update device names to match a non-public device database would be a very brittle solution, not to mention a PITA.

Looking at Strava documentation:
```
A generic “with barometer” device is provided to force the system to use the elevation data from TCX and GPX file types. One only needs to add “with barometer” to the end of the creator name. For example, a TCX file would include something like:
    
        <Creator>
            <Name>My Awesome Device with barometer</Name>
         </Creator> 
```

Just keeping the generic name and adding " with barometer" is enough to fix this issue.  I did a test with the OP activity and it works, Strava enables the option to correct the altitude indicating the data is external.

I think it is a good idea in general since this ensures the altitude data in the GoldenCheetah activity is uploaded, independent of the source or device, since it could be updated, and the user has the option in Strava to change that to Strava estimates.

**Comment by paulj49457** [comment]
Hi Ale,
   Thank you for finding this information, I thought I'd read that section but must have missed it, doh ! 

   I'll update my pull request to append "with barometer" onto the device name for TCX files later today.

   I agree with your view on not changing the names to match a non-public device database, I'm sort of surprised that there isn't a set of published device names, the schema for TCX doesn't specify anything.

Regards,
Paul.

**Comment by amtriathlon** [comment]
Don't worry, I did the change for testing so it is easier just to push it. Additionally I tested the same works for GPX files.
In both cases import to Garmin Connect is preserved, so I think we are ok.
BTW, since strava uploads via API uses TCX format, this change also fixes them.
