### ISSUE TITLE
New feature request: Rowing nk strokecoach .csv support

### ISSUE THREAD

**Issue by achedrien** [GoldenCheetah/GoldenCheetah#3839]
A enorm majority of rower use strokecoach from the brand nk "nielsen kellerman", when sync with computer we can generate from our training a csv or a fit file. The fit file works perfectly well but miss some data specific to rowing that are stored in the scv file. The issue is that the header of the csv file is missread by goldencheetah and therefor is impossible to import. I am sure that this issue affect a lot of rower who would like to be able to follow physiological data as well as rowing technical data presents on the csv files. I attach to this request a typical .csv file generated by a nk strokecpoach (i had to transform it has a xlsx to attach it), to help for any development.
[Timon 20201027 0534.xlsx](https://github.com/GoldenCheetah/GoldenCheetah/files/6108360/Timon.20201027.0534.xlsx)

**Comment by amtriathlon** [comment]
I will put this in the parking lot, meanwhile It is possible to add additional series as XData as explained in https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-DATA#how-external-data-can-be-incorporated-as-xdata

**Comment by amtriathlon** [comment]
We will not develop a custom importer for this case since there seems not to be demand nor developers interested.
OTOH, the FIT file standard allows to add row specific as developer files, in that case they will be automatically imported as XData.
If NK is not willing to do that, it is possible to import CSV data as XData, but the format needs to be adapted as explained in https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-DATA#how-external-data-can-be-incorporated-as-xdata
