### ISSUE TITLE
ANT+ recording: Power phase metrics not recorded.

### ISSUE THREAD

**Issue by awolff64** [GoldenCheetah/GoldenCheetah#3840]
I have a new pair of Favero Assioma power meter pedals.
When recording power with my Garmin Fenix and then import the fit-File I see all metrics in particular the power phase metrics.
When recording power with GC during a training I see all metrics but the power phases.

Would be great if they would be recorded and be present for analysis.

Thanks,
Andreas

**Comment by asendobry** [comment]
This would be fine for me as well. I have the same setup.

Thanks in advance,
Alexander

**Comment by amtriathlon** [comment]
This issue is not specific to the Assioma but Cycling Dynamics was not implemented in Train, there is a Pull Request adding this feature available for testing, an installer for Windows can be downloaded from https://ci.appveyor.com/project/Joern-R/goldencheetah-knhd8/builds/50047523/artifacts, feedback is welcome.
