### ISSUE TITLE
Options defaults change current settings

### ISSUE THREAD

**Issue by shness** [GoldenCheetah/GoldenCheetah#3903]
When opening Options in lower left, some options seem to be changed.  For example, I clicked on options to change units from Imperial to Metric.  When I attempted to save, a dialog popped up saying my I am changing the location of my athlete library but I never changed anything in that field.  After clicking "yes", the fonts also changed.

Note: I changed the font back to what I thought the original value was.  When I open the options now, this behavior is not happening.  Not sure if this happens because a specific file isn't initialized and once done, all is good.

OS X
Version 3.6 Dev-2101

**Comment by amtriathlon** [comment]
> When opening Options in lower left, some options seem to be changed. For example, I clicked on options to change units from Imperial to Metric. When I attempted to save, a dialog popped up saying my I am changing the location of my athlete library but I never changed anything in that field.

This happens when the configured athlete library path is different from the one currently in use, likely because it doesn't exist being the most common case when it is empty.

Perhaps this behaviour was useful at some point it the past, but now it is confusing and likely unnecessary, I propose to remove the second condition below:

https://github.com/GoldenCheetah/GoldenCheetah/blob/3888246b42bc90864be272af8e2065e5f71c1201/src/Gui/ConfigDialog.cpp#L231

**Comment by liversedge** [comment]
The original idea is simply that if the configured athlete directory is different we need to restart to load from the new place- i.e. the user just edited it.

**Comment by amtriathlon** [comment]
The case when the user edited it is correctly detected by the first disjunction part (`shome != general->generalPage->athleteWAS`).
 
It is the second part (`QFileInfo(shome).absoluteFilePath() != QFileInfo(home.absolutePath()).absolutePath()`) which provokes the behavior the OP reports: when the configured path is invalid (typically empty) and GC startup logic sets the athlete library path by other means (typically default paths), it triggers the warning even when the user has not changed athlete library config.

**Comment by liversedge** [comment]
apologies, sounds like its a mistake !

**Comment by shness** [comment]
I am not sure which fields got set, but I know the font was changed to the first option "Academy Engraved LET".  That would have been pretty funny if I was on Windows and it picked the symbols font.  Thanks for looking into it.

**Comment by amtriathlon** [comment]
> I am not sure which fields got set, but I know the font was changed to the first option "Academy Engraved LET". That would have been pretty funny if I was on Windows and it picked the symbols font. Thanks for looking into it.

This is an independent issue: basefont is updated every time settings are saved, this works Ok when the configured font is currently available in the system, but it changes to the first available otherwise:

https://github.com/GoldenCheetah/GoldenCheetah/blob/d83041282d2920c8cf538e00e6bf7fd9f1846b3f/src/Gui/Pages.cpp#L1495

We could track the selected font (or index) and update only when it changes to avoid this behavior.
