### ISSUE TITLE
Crash on v3.6 when importing/downloading activities from a non-primary athlete

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4094]
This was reported at the forum and it is easy to reproduce:
1. Start GC opening an athlete
2. Open a second athlete
3. Import or download an activity to the last athlete

Initial debugging shows AbstractView::page() is returning an invalid pointer leading to a crash when it is subsequently used as `this` pointer for perspectives methods, so it seems current perspective is not set when additional athletes are open, but I don’t understand why this happens nor how it should be fixed.

**Comment by liversedge** [comment]
Each view is lazy loaded- so opening an athlete doesn't take ages- this is especially useful when there are lots of views and lots of perspectives in each view.

Because no view has been selected (we are still on the athlete view) then there are no perspectives loaded- which means the current perspective will always be NULL just after opening an athlete on the athlete view.

As a result, we should ignore signals regarding "rideSelected" until the state has been loaded.

Will apply fix and test out over the next couple of days.
