### ISSUE TITLE
xml saving / reading of a Overview KPI Tile corrupt datafilter code

### ISSUE THREAD

**Issue by PonessM** [GoldenCheetah/GoldenCheetah#4113]
1. Create a new KPI Tile with following Code
{ 
   activities("tolower(Equipment) contains "clifton 8\\"", {
     round(metrics(Distance, Today-9999),2);
   });  
}
KPI Shows the correct Value, as example 326,25 km
2. Restart Application
3. KPI Tile shows always 0 because the Code is loaded without \ as shown below
{ 
   activities("tolower(Equipment) contains "clifton 8"", {
     round(metrics(Distance, Today-9999),2);
   });  
}

Greetings Marcel

**Comment by liversedge** [comment]
You cannot embed a quote in a quote, use ' and ' instead.

**Comment by amtriathlon** [comment]
I found using jsonprotect2/jsonunprotect2, introduced in https://github.com/GoldenCheetah/GoldenCheetah/commit/db9623a201a96c4574e03c183bc2b9b38da5d72b, instead of jsonprotect/jsonunprotect to marshal/unmarshall program in KPI and DATATABLE tiles fixes this issue.
It doesn't seem to create further issues, do you agree with this change @liversedge?

**Comment by liversedge** [comment]
Possibly. I think the strategy of using string replace instead of a escaping characters by streaming (i.e. in quotes, not in quotes etc) is the root cause. But if this works better then thats got to be better than it is now?

**Comment by amtriathlon** [comment]
Agree, I will push the change for further testing.
