### ISSUE TITLE
zip import failing for fflate based zip files

### ISSUE THREAD

**Issue by mayfield** [GoldenCheetah/GoldenCheetah#4189]
Full context: https://github.com/101arrowz/fflate/discussions/125#discussioncomment-2284948

Hello, I'm the [Sauce for Strava](https://github.com/SauceLLC/sauce4strava) dev and my next release is going support bulk FIT export in a zip file.  I'm using https://github.com/101arrowz/fflate to create a ZIP bundle in the browser and I've run into an issue trying to load this file directly into GC.  The fflate author and myself haven't root caused it yet, but suspect it might be a spec compliance issue with the qzip contrib code in GC.  I wanted to open this issue for discussion over here in the hopes that a GC dev might have some more insight into the robustness of qzip.

**Comment by mayfield** [comment]
Small update the author of fflate, @101arrowz has done some pretty great triage on this and also found that a few other ZIP programs are incompatible with GC, including 7-Zip and Windows Explorer's ZIP.  His recommendation is to update to something more robust, like 7zip.

Again full context is here, https://github.com/101arrowz/fflate/discussions/125#discussioncomment-2284948

**Comment by liversedge** [comment]
Whilst it is possible to build GC with an alternative to zlib we use the QT provided functions for official builds.
QT uses zlib which has an FAQ here: http://www.zlib.net/zlib_faq.html do look at the entry regarding the PKWARE zip format.

So long as files comply with RFC1950,1951 and 1952 we should support them- do let us know if this is a root cause and we will fix. We would gently suggest that any web based tooling might consider it appropriate to support the these RFCs, especially since they are also used by the HTTP compression protocols.

**Comment by liversedge** [comment]
BTW, the wrapper code for zlib is included in the contrib directory here if you want to look at how it works:
https://github.com/GoldenCheetah/GoldenCheetah/blob/master/contrib/qzip/zip.cpp

**Comment by 101arrowz** [comment]
The data coming from `fflate` and 7zip is compressed correctly according to the compression RFCs. The problem lies not in Zlib but in the way ZIP entries are handled in GC's code.

Specifically, empty entries like `folder/` are often used for directory names, but as far as I can tell GC attempts to create files with those names and subsequently crashes. Since a huge majority of ZIPs include directories as entries, it would be a good idea to filter them out when extracting ZIPs in GC.

**Comment by liversedge** [comment]
So the issue is actually extracting files that are in sub-folders ?

**Comment by amtriathlon** [comment]
@mayfield: according to https://github.com/101arrowz/fflate/discussions/125#discussioncomment-2285223 it seems you have fixed your issue avoiding the creation of sub-folders when generating the zip file?

**Comment by mayfield** [comment]
@amtriathlon That's correct.  I only use file entries for my zip exports now.  I believe 7-Zip and Windows Explorer's ZIP are still affected though based on @101arrowz's testing

**Comment by amtriathlon** [comment]
> @amtriathlon That's correct. I only use file entries for my zip exports now. 

Great, that's the way to go, GC import of zip files doesn't support folders currently.

> I believe 7-Zip and Windows Explorer's ZIP are still affected though based on @101arrowz's testing

I tested both and they work without problems, provided you don't use folders inside the zip files, off course.

**Comment by amtriathlon** [comment]
I confirmed both Windows Explorer's ZIP and 7-Zip work, provided you don't use folders either.

**Comment by amtriathlon** [comment]
I did some debugging on this, and the problem is the wrapper code for zlib included in the contrib directory (
https://github.com/GoldenCheetah/GoldenCheetah/blob/master/contrib/qzip/zip.cpp) doesn't consider files of size 0 ending with "/" as directory, it can be seen in:
https://github.com/GoldenCheetah/GoldenCheetah/blob/e738b81c7cf7f64dcd011034e7fde6cc3b13b028/contrib/qzip/zip.cpp#L426
after amending that to consider the alternative dir encoding, setting permissions for the newly created dir fails since they are 0
https://github.com/GoldenCheetah/GoldenCheetah/blob/e738b81c7cf7f64dcd011034e7fde6cc3b13b028/contrib/qzip/zip.cpp#L933
so this needs to be conditioned to `permissions>0`, and then it works as expected without changing GC code.
