### ISSUE TITLE
Norton AV 2012 & 2013 report latest version has a virus

### ISSUE THREAD

**Issue by robertstrom** [GoldenCheetah/GoldenCheetah#438]
Norton AV says that the file has a virus (actually the file is flagged twice)

http://www.symantec.com/security_response/writeup.jsp?docid=2011-102713-4647-99&vid=42297&product=Norton%20Internet%20Security&version=20.2.0.19&plang=sym:EN&layouttype=Retail&buildname=Retail&heartbeatID=8C001729-4D8A-11E0-BD6B-BCAEC5D8FF29&env=prod&vendorid=1000590&plid=2&plgid=2&skup=21260740&skum=21234694&skuf=21228659&endpointid=%7B8C001729-4D8A-11E0-BD6B-BCAEC5D8FF29%7D&partnerid=1000590&lic_type=2&lic_attr=21124114&psn=HJ6R9XRBHFJC&osvers=6.1&oslocale=iso:USA&oslang=iso:ENG&os=windows

and 

http://www.symantec.com/security_response/writeup.jsp?docid=2010-081603-3136-99&vid=42289&product=Norton%20Internet%20Security&version=20.2.0.19&plang=sym:EN&layouttype=Retail&buildname=Retail&heartbeatID=8C001729-4D8A-11E0-BD6B-BCAEC5D8FF29&env=prod&vendorid=1000590&plid=2&plgid=2&skup=21260740&skum=21234694&skuf=21228659&endpointid=%7B8C001729-4D8A-11E0-BD6B-BCAEC5D8FF29%7D&partnerid=1000590&lic_type=2&lic_attr=21124114&psn=HJ6R9XRBHFJC&osvers=6.1&oslocale=iso:USA&oslang=iso:ENG&os=windows

The older version download does not get flagged as having a virus.

Can someone please take a look at this and let me know what is going on and reaching out to Symantec to get this cleared up if this is a false positive.

Thanks,

Robert

**Comment by nickcolloff** [comment]
I have also tried to install 'current stable 32 bit version GC on an old computer as a testbed. I haven't used the computer for years, and it still has a very old version of AVG. This picked up virus Win32/Heri, and tagged it as high severity. Just thought you ought to know this. AV software wouldn't allow me to use the file if I wanted to.

**Comment by liversedge** [comment]
and if you update avg?

**Comment by nickcolloff** [comment]
I am trying to update AVG but having problems linking to the internet, probably due to it being an old system. My son is coming over shortly, who is qualified in XP and all things computing, so he will probably be able to fix. I have checked this virus on the internet with my main laptop, and it seems it was a common issue with old versions of AVG. Apologies if I have flagged up a false problem, but was concerned when it first appeared. Will keep you updated when I have managed to update AVG.Best Regards,NickOn 13 July 2020 at 10:03 Mark Liversedge <notifications@github.com> wrote:   and if you update avg?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nickcolloff** [comment]
Okay. I have, at last, managed to uninstall AVG and reinstall the latest version. The latest stable version of GC installs now withot any issues, but won't run on my machine - not valid Win 32 application. I installed v 3.0.0 and that is running okay. It must be because this computer is so old. So no viruses found on the current version with latest AVG.Many apologies for the false flagging.Best Regards,Nick ColloffOn 13 July 2020 at 10:03 Mark Liversedge <notifications@github.com> wrote:   and if you update avg?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
