### ISSUE TITLE
Updated german translation file

### ISSUE THREAD

**Issue by VfBFan** [GoldenCheetah/GoldenCheetah#4386]
Corrected spelling mistakes, partially revised the grammar and well tested. Source file was from the source code of GoldenCheetah 3.6 Build 5000.

[gc_de.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/12384101/gc_de.zip)

**Comment by marcenGC** [comment]
To double check the translation is always good.

Please do not delete any entries. What was happened in ICalendar. 
With the command `lupdate -no-obsolete src.pro` old entries can be removed.
![Screenshot_20230817_215442](https://github.com/GoldenCheetah/GoldenCheetah/assets/125665140/6a7f2d66-ac09-428a-ad6c-cf324a7ab566)


The Guideline for translators can be find here: https://github.com/GoldenCheetah/GoldenCheetah/wiki/Guidelines-for-translators

**Comment by marcenGC** [comment]
I also check the gc_de.ts from the release v3.6 and the same 23 entries translated of 95.
When I open your files with Qt Linguist there are only 23 entries instead of 95.
When you open your file with Qt Linguist you have a total of 95 entries in ICalendar?

Maybe an `update src.pro` helps to add the missing entries.

**Comment by VfBFan** [comment]
The new uploaded zip-file should be ok and contain all strings. :-)

**Comment by amtriathlon** [comment]
Is the attached file in the OP ready for merging?

**Comment by VfBFan** [comment]
Yep, the file should be fine for merging.

**Comment by amtriathlon** [comment]
Thank you!
