### ISSUE TITLE
Create a new workout - cancel problem

### ISSUE THREAD

**Issue by ZajtiM** [GoldenCheetah/GoldenCheetah#4476]
If you cancel in last step, it creates workout, but without name. Is just .crs or .erg for example.

1. you open Workout Wizard and create workout.
2. then you click on "Finish", which opens window "Save Workout", to select where you want to save it and enter file name.
3. if you click cancel in "Save Workout" window, it saves file without name.

I would expect it to close "Save workout" window so you can change workout. Now you have to create it again, or edit "no name" file in text editor.

I'm using latest DEV build for Linux. 
Build date: Apr 13 2024
Linux Mint 21.1

**Comment by amtriathlon** [comment]
This happens because done() is called unconditionally when you click on Finish:

https://github.com/GoldenCheetah/GoldenCheetah/blob/64c7ce3bd50929db29337467db9b9e7740ec7c4d/src/Train/WorkoutWizard.cpp#L807-L809

To go back on cancel each SaveWorkout method could return a bool to indicate ok/cancel and done() be called only on ok.

Do you plan to work on this?
