### ISSUE TITLE
Stryd CIQ Power stopped being moved to Standard Power

### ISSUE THREAD

**Issue by pepelisbon** [GoldenCheetah/GoldenCheetah#4521]
Starting with Garmin firmware update 19.28 Stryd CIQ Power stopped being moved to Standard Power as usual (CIQ 'Power' -> STANDARD POWER), instead is moved to developer field. (CIQ 'Power' -> DEVELOPER POWER-2).
Previous Garmin firmwares files imported fine.

Attached fr955 v19.28 with Stryd fit file
[Fr955v19.28andStryd.fit.zip](https://github.com/user-attachments/files/16169855/Fr955v19.28andStryd.fit.zip)

**Comment by stryder-runner** [comment]
I'm having the same issue. I'm new here... may I ask how/where you copy the code that can be used as a workaround ? Thanks a lot in advance !

**Comment by amtriathlon** [comment]
> I'm having the same issue. I'm new here... may I ask how/where you copy the code that can be used as a workaround ? Thanks a lot in advance !

Please, use https://groups.google.com/g/golden-cheetah-users if you need help, thank you.

**Comment by amtriathlon** [comment]
I found the problem is the field num changes from the first time the dev field is found (10) to the next (0) and the second check in:

https://github.com/GoldenCheetah/GoldenCheetah/blob/1230dc7c682eac5abed9835e6783f4e07338e4c4/src/FileIO/FitRideFile.cpp#L3923

precludes adding the second instance to the QMap and then the mapping doesn't happen..
Just removing that condition fixes this issue, but I am not sure if it can have unwanted side effects.
Further testing or help is welcome.

**Comment by liversedge** [comment]
Hi Ale- what changes? The local field number or the global one?

**Comment by amtriathlon** [comment]
> Hi Ale- what changes? The local field number or the global one?

Hi Mark, the local one, which is used to build the key to index record_deve_native_fields map.

**Comment by liversedge** [comment]
Hmmm sounds like they have a bug. Will definitely try and look at this over the course of the week

**Comment by amtriathlon** [comment]
Problem is provoked by "Lap Power" filed which comes before "Power" and captures the mapping to standard field:
```
** Developer Field Definition Added 'Lap Power' num 10 Developer id 0 type uint16 native 7 unit Watts scale -1.000000 offset -1
** Developer Field Definition Added 'Power' num 0 Developer id 0 type uint16 native 7 unit Watts scale -1.000000 offset -1
```

**Comment by pepelisbon** [comment]
Thank you
