### ISSUE TITLE
Xdata Series sometimes not created on fitfile import

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4535]
Decoding cyclist position (seated/standing) is not working. This was implemented in https://github.com/GoldenCheetah/GoldenCheetah/pull/4327 but doesn't seem to work.

There is already a test file in the repository at https://github.com/GoldenCheetah/GoldenCheetah/blob/master/test/rides/MultiSport-2019-11-24.fit but no POSITION xdata series is created on import. (The file does contain rider_position data, I've checked)

The LAP and SESSION  xdata series are missing too when importing this file. Might be related, not sure.

I'm using current git master with qt6

**Comment by amtriathlon** [comment]
> The LAP and SESSION xdata series are missing too when importing this file. Might be related, not sure.

I think they are, that has been reported at the forum (see an example in https://groups.google.com/g/golden-cheetah-users/c/dbIRjYtCBoU/m/26rDZWRFAQAJ) and it is not evident to me why it happens since simple debugging shows the FIT data (Lap/Session/Position) is processed as expected, but the corresponding XData series somewhat get lost and are not present in the resulting RideFile and I have no idea why. Ideas or more debugging are welcome.

**Comment by amtriathlon** [comment]
> It's related to the number of data series in the recorded fitfile.

There is no hard limit -much less such a low number- for XData series since they are indexed using a QMap and we have example with much more than 4-5 XData series.

> If I remove a bunch with https://www.fitfiletools.com/#/stripper, I get the LAP, SESSION and POSITION xdata series created as expected.

It is weird, which series did you remove?

**Comment by liversedge** [comment]
Good spot- values of "inf" break the parser as they are non numeric. An isinf/isnan check is likely needed somewhere

**Comment by liversedge** [comment]
> But why are there inf values in the first place? The data in the first section of the diff in [#4535 (comment)](https://github.com/GoldenCheetah/GoldenCheetah/issues/4535#issuecomment-2315974772) seems valid.

That's the point

**Comment by amtriathlon** [comment]
Likely scale is zero in https://github.com/GoldenCheetah/GoldenCheetah/blob/71e3928bc614f3209d9977d90cc50b942999b855/src/FileIO/FitRideFile.cpp#L1919

**Comment by liversedge** [comment]
It should be 0.71111
![image](https://github.com/user-attachments/assets/fde9f83f-ef6f-47be-a52d-83c926307a06)

**Comment by liversedge** [comment]
Checking for non-zero scale resolves the inf issue but the lap data for power phase is off- I suspect there is a deeper issue with the way the developer field is being handled within decodeGeneric()- but sadly don't have any time to look at this

**Comment by amtriathlon** [comment]
It looks like power phase is the only standard field with scale < 1, all other cases seem to be integers, may be an issue while parsing fields.json?

**Comment by liversedge** [comment]
Possibly- or also how we lookup field definitions since they are message specific- and whilst the file references global message number 104 that is slightly different if in a SESSION or a LAP ... I might look later this week as I suspect it is my code that is the problem

**Comment by amtriathlon** [comment]
It is a parsing issue, the problem is in:
https://github.com/GoldenCheetah/GoldenCheetah/blob/71e3928bc614f3209d9977d90cc50b942999b855/src/FileIO/FitRideFile.cpp#L261
since obj["scale"] hast type QJsonValue::String and toDouble() fails returning the default value (0), changing to `toString().toDouble()` fixes the issue.

**Comment by stryder-runner** [comment]
> It is a parsing issue, the problem is in:
> 
> https://github.com/GoldenCheetah/GoldenCheetah/blob/71e3928bc614f3209d9977d90cc50b942999b855/src/FileIO/FitRideFile.cpp#L261
> 
> 
> since obj["scale"] has type QJsonValue::String and toDouble() fails returning the default value (0) in this case, it is weird since it works for integer values, changing to `toString().toDouble()` fixes the issue.

Sorry for asking what will be a stupid question here... but where can I change this code on Golden Cheetah for Windows ? I have both the issue of the laps not visible in GoldenCheetah and the Stryd Power not being reported anymore (since it is not convered as IQ Power, not Power anymore... I see there are fixes but have no idea where to apply those fixes ! Thanks a lot in advance
