### ISSUE TITLE
Re-introduce overwrite files on import

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#621]
That was temporarily deprecated in v3.

**Comment by scr142** [comment]
I'm not sure which files are to overwritten in import (/import, /activity or /cache) and why this might be required, but as I've proposed some changes in the Auto Import dialog recently I'm happy to take a look at this, but will need some more specific information first.

**Comment by amtriathlon** [comment]
Activities are identified by Date+Time, when the file you import collides the process is cancelled with an error message, before v3 the user had the option to overwrite the existing activity, IIRC.

**Comment by paulj49457** [comment]
So the existing overwrite functionality appears to work for all imported files, so is there a requirement to have overwriting selectable for each imported directory, or even per file basis? It would be useful to know before I set off and implement something.

**Comment by liversedge** [comment]
The overwrite on import flag means for all files. Would be good to keep a count and add it to the message at the end, e.g. 1000 files imported, 400 overwritten.

**Comment by paulj49457** [comment]
Hi Mark,
Thank you for the guidance on file overwriting, I also see the commented out code in RideImportWizard.cpp, which is an area which I have worked on quite a lot recently due to #3770 Auto import filtering and file import exclusion. So I'll work on reinstating the optional overwrite capability for all activity files with conflicting times/filenames. I'll base these changes on those in #3770, as I have already a more expanded reporting of importation status (see pics in #3770) and I can extend this to include overwrites, also building on #3770 will simplify merging the changes back into the main build.
Regards,
Paul.

**Comment by paulj49457** [comment]
This is now implemented in Auto import filtering, file import exclusion and file overwrite option #3770
