### ISSUE TITLE
Watts per Kilogram on Critical power chart is incorrect

### ISSUE THREAD

**Issue by MarcAmick** [GoldenCheetah/GoldenCheetah#677]
On the Critical power chart; if you switch the data series to Watts Per Kilogram it does not display the correct value.  

For example my 

watts per killogram at 5s is dispalyaing as 33.33/kg
when my watts at 5s is 1068 watts and my weight is 170lbs or 77.1 kgs.

watts /kg should be 1065/77.1 = 13.85 w/kg

**Comment by whileyd** [comment]
Hi Mark,

Just adding to this thread as I'm experiencing the same problem.  Running GC 3.1 64bit on a Win8 machine.  I have weight data imported from Withings (btw - how does this relate to the "athlete weight" entered in the options settings?).

As with Marc, the w/kg histogram in the trends section gives correct data.  Also CP for just Power gives the correct data (~235W CP), but when flipping this to w/kg, the chart and table give wrong data.  CP shows as 7.13 w/kg, implying a 33.1kg weight rather than the 69.9kg entered into the athlete options.
Some screengrabs (hopefully this works):
![image](https://cloud.githubusercontent.com/assets/10565840/5783075/dfc8ef7e-9d74-11e4-824c-d484c4a6255d.png)

![image](https://cloud.githubusercontent.com/assets/10565840/5783097/03df72c0-9d75-11e4-994c-dd4790cd77b7.png)

![image](https://cloud.githubusercontent.com/assets/10565840/5783107/17c08234-9d75-11e4-84c2-6c18c474ad2f.png)

![image](https://cloud.githubusercontent.com/assets/10565840/5783144/67591496-9d75-11e4-80a3-447266e118dd.png)

![image](https://cloud.githubusercontent.com/assets/10565840/5783162/85304a3e-9d75-11e4-8cf5-bcec5f62a44b.png)


Cheers,
Dan.

p.s. still getting my head around GC, which is absolutely amazing. :-)
