### ISSUE TITLE
Wrong formula for Aerobic Decoupling (?)

### ISSUE THREAD

**Issue by cernst72** [GoldenCheetah/GoldenCheetah#721]
It seems there is something screwed up in AerobicDecoupling.cpp, line 90.

The correct formula should be:
  percent = 100%_(eff_1-eff_2)/eff_1  (where eff_i = P_i/HR_i)
Note that this is mathematically equivalent to
  percent = 100%_(1-eff_2/eff_1)  (because 1=eff_1/eff_1)
The latter is expression is a meaningful one: the Aer. decoupling is the ratio of the efficiency of both halves. if eff2>eff1 percent is negative, which is good from a sportive sense of view.
(see e.g. here for more details: http://www.endurancecorner.com/decoupling)

Golden Cheetah is doing something different. First it calculates eff_i^(-1) = HR_i/P_i
(note: HR/P not P/HR, which would be more meaningful). And then
 percent= 100%_(eff_2^(-1)-eff_1^(-1))/eff_1^(-1) = 100%_(eff_2^(-1)/eff_1^(-1)-1) = 100%(eff_1/eff_2-1)
This is not the same!

Example: 
Let's consider eff_1=1.5= const. and say percent/100.=y and eff_2=x
Then we have
 y_friel=(1-x/1.5) and
 y_gc=(1.5/x-1)
For a plot see:
http://www.wolframalpha.com/input/?i=plot%28+1-x%2F1.5%2C+1.5%2Fx-1++from+0.5+to+2.5%29  (blue line=y_friel, purple curve=y_gc)
Both formula do not differ very much around eff_1=eff_2 (i.e. x around 1.5). But if the second half is weaker (smaller x) GoldenCheetah tends to overestimate the size of the decoupling. And if the decoupling is good eff_2>eff_1 i.e.  x > 1.5 GoldenCheetah makes us slightly less fit. :-)

I really seems that GC is not in accordance to the Bible and it's not showing Aerobic Decoupling in a Friel sense. But maybe there is purpose?

If not, to make things short I would recommend making he following changes
            double firstHalfRatio = firstHalfPower / firstHalfHR;
            double secondHalfRatio = secondHalfPower / secondHalfHR;
            percent = 100.0 \* (firstHalfRatio - secondHalfRatio) / firstHalfRatio;

Additionally the Link in the header comment has changed slightly: http://www.trainingbible.com/bkp-all/pdf/AeT_Training.pdf

**Comment by atoponce** [comment]
I know this issue is almost 10 years old, and closed, but I this math is incorrect:

```
double firstHalfRatio = firstHalfPower / firstHalfHR;
double secondHalfRatio = secondHalfPower / secondHalfHR;
percent = 100.0 * (firstHalfRatio - secondHalfRatio) / firstHalfRatio;
```

Aerobic decoupling, or heart rate drift, assumes that the heart rate is increasing (decoupling) from your pace as the distance increases. If the heart rate decreases, then either the activity is getting easier such as running downhill, or the athlete found a way to exercise more efficiently later in the activity. So, assuming the heart rate will always be increasing, then we can assume that HR₂ > HR₁ for a constant effort.

If you were to run on a treadmill at a constant pace, then we can look strictly at HR. If HR₂ > HR₁, then:

    HR₂ - HR₁ = difference

To get a percentage increase from HR₁, we just divide the difference from HR₁:

    100 * (HR₂ - HR₁) / HR₁ = % of increase

Adding pace complicates things, but not too badly if you keep your units straight. Because heart rate is measured in beats per minute and pace is measured in minutes per mile (or minutes per km), then we'd be interested in the average HR beats per mile (or km).

Looking strictly at the units, the minutes cancel out, and we're left with "beats per mile":

```
  beats / minute * minutes / mile
= beats / m̶i̶n̶u̶t̶e̶ * m̶i̶n̶u̶t̶e̶s̶ / mile
= beats / mile 
```

This makes sense. If I'm running an average of 8 minutes per mile and my heart rate averages 140 beats per minute, then I know that my heart beat 140 \* 8 = 1,120 times over that mile. My heart is beating "1120 beats per mile".

So the formula for accurate Pa:Hr would be:

```
100 * (HR₂ * Pace₂ - HR₁ * Pace₁) / (HR₁ * Pace₁) = Pa:Hr
```

However, if you have power, the math gets a touch more tricky. 1 Watt = 1 Joule per second = 60 Joules per minute. Because both HR and power have the time unit in the denominator, and because we would be interested in "beats per Joule" (or "beats per Watt"), we would divide the values.

Again, looking at the unit math:

```
  (beats / minute) / (Joules / minute)
= beats / minute * 1/(Joules / minute) 
= beats / minute * minutes / Joule
= beats / m̶i̶n̶u̶t̶e̶ * m̶i̶n̶u̶t̶e̶s̶ / Joule
= beats / Joule
```

We could either divide our HR by 60 to get bets per second or multiply the Watts by 60 to get Joules per minute, but when you're dealing with ratios, it turns out this is unnecessary. [Here's the proof](https://www.wolframalpha.com/input?i=%28x1%2F%2860*y1%29%2F%28x2%2F%2860*y2%29%29+%3D+%28x1%2Fy1%29%2F%28x2%2Fy2%29):

      (HR₁/(60*W₁) / (HR₂/(60*W₂))
    = (HR₁/W₁*1/60) / (HR₂/W₂*1/60)
    = 1/60*(HR₁/W₁) / [1/60*(HR₂/W₂)]
    = 1/60 * 60 * (HR₁/W₁) / (HR₂/W₂)
    = (HR₁/W₁) / (HR₂/W₂)

So we can just skip that math and divide HR by Watts, even if the time units differ. So the correct formula for Pw:Hr would be:

```
100 * (HR₂/W₂ - HR₁/W₁) / (HR₁/W₁) = Pw:Hr
```

With these formulas, positive Pa:Hr and Pw:Hr values will always indicate that the latter half of the activity required more effort than the first half (the decoupling is increasing). If the values are negative, this indicates the latter half of the activity required less effort than the first half (the decoupling is decreasing).
