### ISSUE TITLE
Re-Architect Train View

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#974]
The architecture is basically flawed; we have controllers and devices in GC but in reality we have controllers (e.g. ANT) and devices (e.g. Power, S+C) and capabilities (e.g. Power, Cadence, Brake)

Need to completely change the 'discover / pair / choose' paradigm.

We can discover sensors as needed without having to configure them in advance but in corollary we should be able to save a setup to choose specific capabilities from multiple devices (e.g. ct brake but srm power).

**Comment by vlcvboyer** [comment]
Hi,

see attached my draft for device pairing:

![image](https://cloud.githubusercontent.com/assets/13483855/11912862/dbb6a562-a650-11e5-9ffe-6e6b6d066d08.png)

There is a button called "data source precedence" in used to re-order (and disable) data recorded by GC (typ. if one sensor have to be disabled (not magnet on wheel when on trainer, etc.).

It will be fine also to have a unique device_list in the code (at present there is deviceConfiguration list and few controllers but each device is not listed (every ANT sensor, etc.). Then each device is linked to a controller, etc.
It does not allow clean code for calibration

**Comment by liversedge** [comment]
To replace the existing dialog in Preferences?

I can't quite work out what this dialog adds to that?

Can you explain a little ?

**Comment by vlcvboyer** [comment]
Based on several feature request it is mostly to 
- allow disabling one data from a sensor (typ. speed data from SPD&CAD sensor when used on trainer without wheel or magnet on wheel). 
- be able to reorder data sources (typ.: regarding to speed a trainer is more accurate than a garmin accelerometer speed sensor but cadence from trainer may be wrong as it assumes gear ratio is constant thus it is useful to pick different values from different sensors)
- be able to use several controllers at the same time (computrainer + ANT, etc.). I saw that it is already done? I do not understand how to activate it. Can you give me more details?
- enable "auto-pairing" of any discovered sensor
- show sensors that were paired during previous session (useful for troubleshooting) and name them
- add virtual sensors (speed is already there at present but cannot be used like any other speed sensor). This can be extended with virtual distance (I'll need it personnally for more accurate video synchronization) and virtual power (don't know if this will be useful for someone or maybe it is already included).

Existing Device configuration remain there as a preset.

The two first are not shown above but should use the same layout. However the button to access those details is shown: "Data sourcer precedence"

I've included "parameters" button but we should prefer global settings (typ. "cyclist weight" or "wheel diameter"). I think that there are no sensors with specific parameters.

I've used VBA dialog instead of QT as it is just a draft!

I proposed this because I saw several features request and at the same time I had some trouble with code related to devices. Typ. there is a mix between DeviceConfigutation and Device that do not allow a clean and consistent code for devices calibration.

**Comment by liversedge** [comment]
this is unlikely to happen. 

the functionality is "good enough". more advance offerings from peripedal, trainer road and zwift et al leave GC train view as a useful (and free) option. But more advanced users are likely to use a paid for product for this.
